'use client';

import { useRouter } from 'next/navigation';
import { AppLogoMarkIcon } from '@/app/sharedIcons';

export default function TermsPage() {
  const router = useRouter();

  return (
    <main className="page" style={{ maxWidth: '800px', margin: '40px auto', padding: '0 20px' }}>
      <button 
        className="btn btn-secondary" 
        onClick={() => router.back()} 
        style={{ marginBottom: '24px', width: 'auto', padding: '8px 16px' }}
      >
        ← Go Back
      </button>

      <header className="page-header" style={{ marginBottom: '32px' }}>
        <div className="logo"><AppLogoMarkIcon size={24} /><span>RAPP</span></div>
        <h1 className="page-title" style={{ fontSize: '2.5rem', fontWeight: 900, marginTop: '16px' }}>Terms of Service</h1>
        <p className="text-muted">Last Updated: July 15, 2026</p>
      </header>

      <div className="card" style={{ padding: '32px', display: 'flex', flexDirection: 'column', gap: '24px' }}>
        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>1. Automotive Repair Risk & Liability</h2>
          <p className="text-muted" style={{ lineHeight: '1.6' }}>
            Automotive maintenance, modifications, and repair are inherently dangerous activities. They involve heavy machinery, high temperatures, toxic chemicals, electrical currents, and high-pressure systems. By accessing and using the service guides, diagnostics, and documentation provided by RAPP, you explicitly assume 100% of the physical, financial, and mechanical risks associated with undertaking these repairs yourself.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>2. Disclaimer of Warranties &amp; &quot;As-Is&quot; Provision</h2>
          <p className="text-muted" style={{ lineHeight: '1.6' }}>
            RAPP is an artificial intelligence-driven repair engine utilizing Large Language Models (LLMs) and Vector Databases. All procedures, torque specifications, electrical wiring diagrams, and parts recommendations are provided &quot;as-is&quot; and &quot;as-available&quot; without warranties of any kind, either express or implied, including but not limited to warranties of accuracy, completeness, safety, or suitability for any particular purpose.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>3. Limitation of Liability</h2>
          <p className="text-muted" style={{ lineHeight: '1.6' }}>
            Under no circumstances shall RAPP, its developers, operators, or affiliates be liable for any direct, indirect, incidental, special, consequential, or punitive damages. This includes, without limitation, personal injury, death, property damage, vehicle failure, engine destruction, towing costs, or financial losses resulting from the use of, or inability to use, the information generated by the RAPP repair platform.
          </p>
        </section>

        <section>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#fff', marginBottom: '8px' }}>4. Safety First Requirement</h2>
          <p className="text-muted" style={{ lineHeight: '1.6' }}>
            You agree to wear certified personal protective equipment (safety goggles, thick gloves, closed-toe shoes) and to employ appropriate safety gear (sturdy jack stands, wheel chocks, battery terminal isolators) at all times when working under a vehicle. If you do not possess the necessary physical tools, equipment, or comfort level to complete a job safely, you must cease repair immediately and redirect your vehicle to a certified professional technician.
          </p>
        </section>
      </div>
    </main>
  );
}
