export interface ObdCode {
  code: string;
  category: 'P' | 'B' | 'C' | 'U';
  description: string;
}

// Curated set of common generic (SAE) OBD-II codes across Powertrain, Body,
// Chassis, and Network categories. This intentionally does not attempt to
// enumerate every manufacturer-specific code -- it covers the codes a
// consumer-grade scanner surfaces in the overwhelming majority of cases.
export const OBD_CODES: ObdCode[] = [
  // ── P0100–P0199: Fuel & Air Metering ──────────────────────────────────
  { code: 'P0100', category: 'P', description: 'Mass or Volume Air Flow Circuit Malfunction' },
  { code: 'P0101', category: 'P', description: 'Mass or Volume Air Flow Circuit Range/Performance' },
  { code: 'P0102', category: 'P', description: 'Mass or Volume Air Flow Circuit Low Input' },
  { code: 'P0103', category: 'P', description: 'Mass or Volume Air Flow Circuit High Input' },
  { code: 'P0106', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance' },
  { code: 'P0107', category: 'P', description: 'Manifold Absolute Pressure Circuit Low Input' },
  { code: 'P0108', category: 'P', description: 'Manifold Absolute Pressure Circuit High Input' },
  { code: 'P0111', category: 'P', description: 'Intake Air Temperature Circuit Range/Performance' },
  { code: 'P0112', category: 'P', description: 'Intake Air Temperature Circuit Low Input' },
  { code: 'P0113', category: 'P', description: 'Intake Air Temperature Circuit High Input' },
  { code: 'P0116', category: 'P', description: 'Engine Coolant Temperature Circuit Range/Performance' },
  { code: 'P0117', category: 'P', description: 'Engine Coolant Temperature Circuit Low Input' },
  { code: 'P0118', category: 'P', description: 'Engine Coolant Temperature Circuit High Input' },
  { code: 'P0121', category: 'P', description: 'Throttle Position Sensor Circuit Range/Performance' },
  { code: 'P0122', category: 'P', description: 'Throttle Position Sensor Circuit Low Input' },
  { code: 'P0123', category: 'P', description: 'Throttle Position Sensor Circuit High Input' },
  { code: 'P0128', category: 'P', description: 'Coolant Thermostat Below Regulating Temperature' },
  { code: 'P0130', category: 'P', description: 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)' },
  { code: 'P0131', category: 'P', description: 'O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)' },
  { code: 'P0132', category: 'P', description: 'O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)' },
  { code: 'P0133', category: 'P', description: 'O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)' },
  { code: 'P0134', category: 'P', description: 'O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)' },
  { code: 'P0135', category: 'P', description: 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)' },
  { code: 'P0136', category: 'P', description: 'O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)' },
  { code: 'P0141', category: 'P', description: 'O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)' },
  { code: 'P0150', category: 'P', description: 'O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)' },
  { code: 'P0155', category: 'P', description: 'O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 1)' },
  { code: 'P0171', category: 'P', description: 'System Too Lean (Bank 1)' },
  { code: 'P0172', category: 'P', description: 'System Too Rich (Bank 1)' },
  { code: 'P0174', category: 'P', description: 'System Too Lean (Bank 2)' },
  { code: 'P0175', category: 'P', description: 'System Too Rich (Bank 2)' },
  { code: 'P0176', category: 'P', description: 'Fuel Composition Sensor Circuit Malfunction' },
  { code: 'P0180', category: 'P', description: 'Fuel Temperature Sensor A Circuit Malfunction' },

  // ── P0200–P0299: Fuel & Air Metering — Injector Circuit ──────────────
  { code: 'P0200', category: 'P', description: 'Injector Circuit Malfunction' },
  { code: 'P0201', category: 'P', description: 'Injector Circuit Malfunction — Cylinder 1' },
  { code: 'P0202', category: 'P', description: 'Injector Circuit Malfunction — Cylinder 2' },
  { code: 'P0203', category: 'P', description: 'Injector Circuit Malfunction — Cylinder 3' },
  { code: 'P0204', category: 'P', description: 'Injector Circuit Malfunction — Cylinder 4' },
  { code: 'P0217', category: 'P', description: 'Engine Overtemperature Condition' },
  { code: 'P0219', category: 'P', description: 'Engine Overspeed Condition' },
  { code: 'P0230', category: 'P', description: 'Fuel Pump Primary Circuit Malfunction' },
  { code: 'P0231', category: 'P', description: 'Fuel Pump Secondary Circuit Low' },
  { code: 'P0232', category: 'P', description: 'Fuel Pump Secondary Circuit High' },
  { code: 'P0261', category: 'P', description: 'Cylinder 1 Injector Circuit Low' },
  { code: 'P0262', category: 'P', description: 'Cylinder 1 Injector Circuit High' },

  // ── P0300–P0399: Ignition System / Misfire ────────────────────────────
  { code: 'P0300', category: 'P', description: 'Random/Multiple Cylinder Misfire Detected' },
  { code: 'P0301', category: 'P', description: 'Cylinder 1 Misfire Detected' },
  { code: 'P0302', category: 'P', description: 'Cylinder 2 Misfire Detected' },
  { code: 'P0303', category: 'P', description: 'Cylinder 3 Misfire Detected' },
  { code: 'P0304', category: 'P', description: 'Cylinder 4 Misfire Detected' },
  { code: 'P0305', category: 'P', description: 'Cylinder 5 Misfire Detected' },
  { code: 'P0306', category: 'P', description: 'Cylinder 6 Misfire Detected' },
  { code: 'P0325', category: 'P', description: 'Knock Sensor Circuit Malfunction (Bank 1)' },
  { code: 'P0327', category: 'P', description: 'Knock Sensor Circuit Low Input (Bank 1)' },
  { code: 'P0328', category: 'P', description: 'Knock Sensor Circuit High Input (Bank 1)' },
  { code: 'P0335', category: 'P', description: 'Crankshaft Position Sensor Circuit Malfunction' },
  { code: 'P0336', category: 'P', description: 'Crankshaft Position Sensor Circuit Range/Performance' },
  { code: 'P0339', category: 'P', description: 'Crankshaft Position Sensor Circuit Intermittent' },
  { code: 'P0340', category: 'P', description: 'Camshaft Position Sensor Circuit Malfunction' },
  { code: 'P0341', category: 'P', description: 'Camshaft Position Sensor Circuit Range/Performance' },
  { code: 'P0350', category: 'P', description: 'Ignition Coil Primary/Secondary Circuit Malfunction' },
  { code: 'P0351', category: 'P', description: 'Ignition Coil A Primary/Secondary Circuit Malfunction' },
  { code: 'P0352', category: 'P', description: 'Ignition Coil B Primary/Secondary Circuit Malfunction' },
  { code: 'P0353', category: 'P', description: 'Ignition Coil C Primary/Secondary Circuit Malfunction' },
  { code: 'P0354', category: 'P', description: 'Ignition Coil D Primary/Secondary Circuit Malfunction' },

  // ── P0400–P0499: Emission Control ─────────────────────────────────────
  { code: 'P0400', category: 'P', description: 'Exhaust Gas Recirculation Flow Malfunction' },
  { code: 'P0401', category: 'P', description: 'Exhaust Gas Recirculation Flow Insufficient Detected' },
  { code: 'P0402', category: 'P', description: 'Exhaust Gas Recirculation Flow Excessive Detected' },
  { code: 'P0404', category: 'P', description: 'Exhaust Gas Recirculation Circuit Range/Performance' },
  { code: 'P0410', category: 'P', description: 'Secondary Air Injection System Malfunction' },
  { code: 'P0420', category: 'P', description: 'Catalyst System Efficiency Below Threshold (Bank 1)' },
  { code: 'P0421', category: 'P', description: 'Warm Up Catalyst Efficiency Below Threshold (Bank 1)' },
  { code: 'P0430', category: 'P', description: 'Catalyst System Efficiency Below Threshold (Bank 2)' },
  { code: 'P0440', category: 'P', description: 'Evaporative Emission Control System Malfunction' },
  { code: 'P0441', category: 'P', description: 'Evaporative Emission Control System Incorrect Purge Flow' },
  { code: 'P0442', category: 'P', description: 'Evaporative Emission Control System Leak Detected (small leak)' },
  { code: 'P0446', category: 'P', description: 'Evaporative Emission Control System Vent Control Circuit Malfunction' },
  { code: 'P0450', category: 'P', description: 'Evaporative Emission Control System Pressure Sensor Malfunction' },
  { code: 'P0455', category: 'P', description: 'Evaporative Emission Control System Leak Detected (large leak)' },
  { code: 'P0456', category: 'P', description: 'Evaporative Emission Control System Leak Detected (very small leak)' },
  { code: 'P0460', category: 'P', description: 'Fuel Level Sensor Circuit Malfunction' },
  { code: 'P0463', category: 'P', description: 'Fuel Level Sensor Circuit High Input' },
  { code: 'P0480', category: 'P', description: 'Cooling Fan 1 Control Circuit Malfunction' },
  { code: 'P0481', category: 'P', description: 'Cooling Fan 2 Control Circuit Malfunction' },

  // ── P0500–P0599: Vehicle Speed / Idle Control ─────────────────────────
  { code: 'P0500', category: 'P', description: 'Vehicle Speed Sensor Malfunction' },
  { code: 'P0505', category: 'P', description: 'Idle Air Control System Malfunction' },
  { code: 'P0506', category: 'P', description: 'Idle Air Control System RPM Lower Than Expected' },
  { code: 'P0507', category: 'P', description: 'Idle Air Control System RPM Higher Than Expected' },
  { code: 'P0520', category: 'P', description: 'Engine Oil Pressure Sensor/Switch Circuit Malfunction' },
  { code: 'P0522', category: 'P', description: 'Engine Oil Pressure Sensor/Switch Low Voltage' },
  { code: 'P0523', category: 'P', description: 'Engine Oil Pressure Sensor/Switch High Voltage' },
  { code: 'P0530', category: 'P', description: 'A/C Refrigerant Pressure Sensor Circuit Malfunction' },
  { code: 'P0562', category: 'P', description: 'System Voltage Low' },
  { code: 'P0563', category: 'P', description: 'System Voltage High' },

  // ── P0600–P0699: Computer Output Circuit ──────────────────────────────
  { code: 'P0600', category: 'P', description: 'Serial Communication Link Malfunction' },
  { code: 'P0601', category: 'P', description: 'Internal Control Module Memory Check Sum Error' },
  { code: 'P0603', category: 'P', description: 'Internal Control Module Keep Alive Memory Error' },
  { code: 'P0605', category: 'P', description: 'Internal Control Module Read Only Memory Error' },
  { code: 'P0606', category: 'P', description: 'ECM/PCM Processor Fault' },
  { code: 'P0617', category: 'P', description: 'Starter Relay Circuit High' },

  // ── P0700–P0799: Transmission ─────────────────────────────────────────
  { code: 'P0700', category: 'P', description: 'Transmission Control System Malfunction' },
  { code: 'P0701', category: 'P', description: 'Transmission Control System Range/Performance' },
  { code: 'P0702', category: 'P', description: 'Transmission Control System Electrical' },
  { code: 'P0703', category: 'P', description: 'Torque Converter/Brake Switch B Circuit Malfunction' },
  { code: 'P0705', category: 'P', description: 'Transmission Range Sensor Circuit Malfunction (PRNDL Input)' },
  { code: 'P0706', category: 'P', description: 'Transmission Range Sensor Circuit Range/Performance' },
  { code: 'P0710', category: 'P', description: 'Transmission Fluid Temperature Sensor Circuit Malfunction' },
  { code: 'P0715', category: 'P', description: 'Input/Turbine Speed Sensor Circuit Malfunction' },
  { code: 'P0720', category: 'P', description: 'Output Speed Sensor Circuit Malfunction' },
  { code: 'P0730', category: 'P', description: 'Incorrect Gear Ratio' },
  { code: 'P0731', category: 'P', description: 'Gear 1 Incorrect Ratio' },
  { code: 'P0732', category: 'P', description: 'Gear 2 Incorrect Ratio' },
  { code: 'P0733', category: 'P', description: 'Gear 3 Incorrect Ratio' },
  { code: 'P0734', category: 'P', description: 'Gear 4 Incorrect Ratio' },
  { code: 'P0740', category: 'P', description: 'Torque Converter Clutch Circuit Malfunction' },
  { code: 'P0741', category: 'P', description: 'Torque Converter Clutch Circuit Performance or Stuck Off' },
  { code: 'P0750', category: 'P', description: 'Shift Solenoid A Malfunction' },
  { code: 'P0755', category: 'P', description: 'Shift Solenoid B Malfunction' },
  { code: 'P0760', category: 'P', description: 'Shift Solenoid C Malfunction' },

  // ── Common Manufacturer / Network P1xxx examples ──────────────────────
  { code: 'P1000', category: 'P', description: 'OBD-II Monitor Testing Not Complete (Manufacturer Specific)' },
  { code: 'P1101', category: 'P', description: 'Mass Air Flow Sensor Out of Self-Test Range (Ford)' },
  { code: 'P1300', category: 'P', description: 'Ignition Coil Primary Circuit Malfunction (Manufacturer Specific)' },
  { code: 'P1450', category: 'P', description: 'Unable to Bleed Up Fuel Tank Vacuum (Manufacturer Specific)' },

  // ── B0xxx: Body ─────────────────────────────────────────────────────
  { code: 'B0001', category: 'B', description: 'Driver Frontal Stage 1 Deployment Control' },
  { code: 'B0010', category: 'B', description: 'Passenger Frontal Stage 1 Deployment Control' },
  { code: 'B0020', category: 'B', description: 'Driver Side Deployment Control' },
  { code: 'B0030', category: 'B', description: 'Passenger Side Deployment Control' },
  { code: 'B0051', category: 'B', description: 'Driver Seat Belt Switch Circuit' },
  { code: 'B0052', category: 'B', description: 'Passenger Seat Belt Switch Circuit' },
  { code: 'B0080', category: 'B', description: 'Left Side Curtain Deployment Control' },
  { code: 'B0081', category: 'B', description: 'Right Side Curtain Deployment Control' },
  { code: 'B0092', category: 'B', description: 'Frontal Crash Sensor Circuit' },
  { code: 'B0100', category: 'B', description: 'Occupant Classification System Circuit' },
  { code: 'B0111', category: 'B', description: 'Front Sensor Internal Fault' },
  { code: 'B1000', category: 'B', description: 'ECU Malfunction (Body Control Module)' },
  { code: 'B1318', category: 'B', description: 'Battery Voltage Low' },
  { code: 'B1342', category: 'B', description: 'ECU / Module Is Defective' },
  { code: 'B1519', category: 'B', description: 'Battery/Power Feed to Sensing/Diagnostic Module Circuit' },
  { code: 'B2477', category: 'B', description: 'Door Ajar Switch Circuit' },
  { code: 'B2800', category: 'B', description: 'Anti-Theft System Fault' },
  { code: 'B1650', category: 'B', description: 'Climate Control Blower Motor Circuit Malfunction' },
  { code: 'B1651', category: 'B', description: 'HVAC Blend Door Actuator Circuit Malfunction' },
  { code: 'B1004', category: 'B', description: 'Power Window Switch Circuit Malfunction' },

  // ── C0xxx: Chassis ──────────────────────────────────────────────────
  { code: 'C0035', category: 'C', description: 'Left Front Wheel Speed Sensor Circuit' },
  { code: 'C0040', category: 'C', description: 'Right Front Wheel Speed Sensor Circuit' },
  { code: 'C0045', category: 'C', description: 'Left Rear Wheel Speed Sensor Circuit' },
  { code: 'C0050', category: 'C', description: 'Right Rear Wheel Speed Sensor Circuit' },
  { code: 'C0055', category: 'C', description: 'Yaw Rate Sensor Circuit Malfunction' },
  { code: 'C0060', category: 'C', description: 'Left Front ABS Solenoid #1 Circuit' },
  { code: 'C0065', category: 'C', description: 'Right Front ABS Solenoid #1 Circuit' },
  { code: 'C0110', category: 'C', description: 'Pump Motor Circuit Malfunction (ABS)' },
  { code: 'C0121', category: 'C', description: 'Valve Relay Circuit Malfunction (ABS)' },
  { code: 'C0161', category: 'C', description: 'Traction Control System Disabled Switch Circuit' },
  { code: 'C0200', category: 'C', description: 'Steering Angle Sensor Circuit Malfunction' },
  { code: 'C0221', category: 'C', description: 'Left Front Wheel Speed Out of Range' },
  { code: 'C0245', category: 'C', description: 'Right Rear Wheel Speed Out of Range' },
  { code: 'C0300', category: 'C', description: 'Traction Control System Malfunction' },
  { code: 'C0450', category: 'C', description: 'Brake Pedal Travel Sensor Circuit Malfunction' },
  { code: 'C0561', category: 'C', description: 'Calibration/Configuration Data Incompatible (Chassis Module)' },
  { code: 'C0710', category: 'C', description: 'Low Tire Pressure — Left Front' },
  { code: 'C0715', category: 'C', description: 'Low Tire Pressure — Right Front' },
  { code: 'C0720', category: 'C', description: 'Low Tire Pressure — Left Rear' },
  { code: 'C0725', category: 'C', description: 'Low Tire Pressure — Right Rear' },
  { code: 'C0800', category: 'C', description: 'TPMS Sensor Battery Low' },

  // ── U0xxx: Network / Communication ─────────────────────────────────
  { code: 'U0001', category: 'U', description: 'High Speed CAN Communication Bus' },
  { code: 'U0100', category: 'U', description: 'Lost Communication with ECM/PCM' },
  { code: 'U0101', category: 'U', description: 'Lost Communication with TCM' },
  { code: 'U0121', category: 'U', description: 'Lost Communication with ABS Control Module' },
  { code: 'U0140', category: 'U', description: 'Lost Communication with Body Control Module' },
  { code: 'U0155', category: 'U', description: 'Lost Communication with Instrument Panel Cluster' },
  { code: 'U0164', category: 'U', description: 'Lost Communication with HVAC Control Module' },
  { code: 'U0184', category: 'U', description: 'Lost Communication with Radio' },
  { code: 'U0195', category: 'U', description: 'Lost Communication with Battery Energy Control Module' },
  { code: 'U0300', category: 'U', description: 'Internal Control Module Software Incompatibility' },
  { code: 'U0401', category: 'U', description: 'Invalid Data Received From ECM/PCM' },
  { code: 'U0402', category: 'U', description: 'Invalid Data Received From TCM' },
  { code: 'U0415', category: 'U', description: 'Invalid Data Received From ABS Control Module' },
  { code: 'U0422', category: 'U', description: 'Invalid Data Received From Body Control Module' },
  { code: 'U1000', category: 'U', description: 'Class 2 Communication Malfunction (Manufacturer Specific)' },
];

export function searchObdCodes(query: string, limit = 8): ObdCode[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  const results = OBD_CODES.filter(
    (c) => c.code.startsWith(q) || c.description.toUpperCase().includes(q)
  );
  return results.slice(0, limit);
}
