export interface ObdCode {
  code: string;
  category: 'P' | 'B' | 'C' | 'U';
  description: string;
}

// Generic (SAE J2012 / ISO 15031-6) OBD-II codes across Powertrain, Body,
// Chassis, and Network categories. This intentionally does not attempt to
// enumerate manufacturer-specific codes (aside from a few labeled P1xxx
// examples below) -- only the standard codes every scanner surfaces.
//
// P-codes (P0000-P0799) sourced from lennykean/OBDII.DTC (MIT license),
// github.com/lennykean/OBDII.DTC, filtered to decimal-only generic codes
// (excludes rare hex-suffixed extended codes real consumer scanners don't
// surface). B/C/U categories are still the original smaller curated set --
// same source has full B/C/U data if that gets expanded later too.
export const OBD_CODES: ObdCode[] = [
  // ── P0000–P0099: General / OBD Monitoring ─────────────────────────────
  { code: 'P0000', category: 'P', description: 'No Fault Detected' },
  { code: 'P0001', category: 'P', description: 'Fuel Volume Regulator A Control Circuit/Open' },
  { code: 'P0002', category: 'P', description: 'Fuel Volume Regulator A Control Circuit Performance' },
  { code: 'P0003', category: 'P', description: 'Fuel Volume Regulator A Control Circuit Low' },
  { code: 'P0004', category: 'P', description: 'Fuel Volume Regulator A Control Circuit High' },
  { code: 'P0005', category: 'P', description: 'Fuel Shutoff Valve A Control Circuit/Open' },
  { code: 'P0006', category: 'P', description: 'Fuel Shutoff Valve A Control Circuit Low' },
  { code: 'P0007', category: 'P', description: 'Fuel Shutoff Valve A Control Circuit High' },
  { code: 'P0008', category: 'P', description: 'Engine Position System Performance Bank 1' },
  { code: 'P0009', category: 'P', description: 'Engine Position System Performance Bank 2' },
  { code: 'P0010', category: 'P', description: 'A Camshaft Position Actuator A Control Circuit/Open Bank 1' },
  { code: 'P0011', category: 'P', description: 'A Camshaft Position - Timing Over-Advanced or System Performance Bank 1' },
  { code: 'P0012', category: 'P', description: 'A Camshaft Position - Timing Over-Retarded Bank 1' },
  { code: 'P0013', category: 'P', description: 'B Camshaft Position Actuator A Control Circuit/Open Bank 1' },
  { code: 'P0014', category: 'P', description: 'B Camshaft Position - Timing Over-Advanced or System Performance Bank 1' },
  { code: 'P0015', category: 'P', description: 'B Camshaft Position - Timing Over-Retarded Bank 1' },
  { code: 'P0016', category: 'P', description: 'Crankshaft Position - Camshaft Position Correlation Bank 1 Sensor A' },
  { code: 'P0017', category: 'P', description: 'Crankshaft Position - Camshaft Position Correlation Bank 1 Sensor B' },
  { code: 'P0018', category: 'P', description: 'Crankshaft Position - Camshaft Position Correlation Bank 2 Sensor A' },
  { code: 'P0019', category: 'P', description: 'Crankshaft Position - Camshaft Position Correlation Bank 2 Sensor B' },
  { code: 'P0020', category: 'P', description: 'A Camshaft Position Actuator A Control Circuit/Open Bank 2' },
  { code: 'P0021', category: 'P', description: 'A Camshaft Position - Timing Over-Advanced or System Performance Bank 2' },
  { code: 'P0022', category: 'P', description: 'A Camshaft Position - Timing Over-Retarded Bank 2' },
  { code: 'P0023', category: 'P', description: 'B Camshaft Position Actuator A Control Circuit/Open Bank 2' },
  { code: 'P0024', category: 'P', description: 'B Camshaft Position - Timing Over-Advanced or System Performance Bank 2' },
  { code: 'P0025', category: 'P', description: 'B Camshaft Position - Timing Over-Retarded Bank 2' },
  { code: 'P0026', category: 'P', description: 'Intake Valve Control Solenoid Circuit Range/Performance Bank 1' },
  { code: 'P0027', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Range/Performance Bank 1' },
  { code: 'P0028', category: 'P', description: 'Intake Valve Control Solenoid Circuit Range/Performance Bank 2' },
  { code: 'P0029', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Range/Performance Bank 2' },
  { code: 'P0030', category: 'P', description: 'HO2S Heater Control Circuit Bank 1 Sensor 1' },
  { code: 'P0031', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 1 Sensor 1' },
  { code: 'P0032', category: 'P', description: 'HO2S Heater Control Circuit High Bank 1 Sensor 1' },
  { code: 'P0033', category: 'P', description: 'Turbocharger/Supercharger Bypass Valve A Control Circuit' },
  { code: 'P0034', category: 'P', description: 'Turbocharger/Supercharger Bypass Valve A Control Circuit Low' },
  { code: 'P0035', category: 'P', description: 'Turbocharger/Supercharger Bypass Valve A Control Circuit High' },
  { code: 'P0036', category: 'P', description: 'HO2S Heater Control Circuit Bank 1 Sensor 2' },
  { code: 'P0037', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 1 Sensor 2' },
  { code: 'P0038', category: 'P', description: 'HO2S Heater Control Circuit High Bank 1 Sensor 2' },
  { code: 'P0039', category: 'P', description: 'Turbocharger/Supercharger Bypass Valve A Control Circuit Range/Performance' },
  { code: 'P0040', category: 'P', description: 'O2 Sensor Signals Swapped Bank 1 Sensor 1/Bank 2 Sensor 1' },
  { code: 'P0041', category: 'P', description: 'O2 Sensor Signals Swapped Bank 1 Sensor 2/Bank 2 Sensor 2' },
  { code: 'P0042', category: 'P', description: 'HO2S Heater Control Circuit Bank 1 Sensor 3' },
  { code: 'P0043', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 1 Sensor 3' },
  { code: 'P0044', category: 'P', description: 'HO2S Heater Control Circuit High Bank 1 Sensor 3' },
  { code: 'P0045', category: 'P', description: 'Turbocharger/Supercharger Boost Control A Circuit/Open' },
  { code: 'P0046', category: 'P', description: 'Turbocharger/Supercharger Boost Control A Circuit Range/Performance' },
  { code: 'P0047', category: 'P', description: 'Turbocharger/Supercharger Boost Control A Circuit Low' },
  { code: 'P0048', category: 'P', description: 'Turbocharger/Supercharger Boost Control A Circuit High' },
  { code: 'P0049', category: 'P', description: 'Turbocharger/Supercharger A Turbine Overspeed' },
  { code: 'P0050', category: 'P', description: 'HO2S Heater Control Circuit Bank 2 Sensor 1' },
  { code: 'P0051', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 2 Sensor 1' },
  { code: 'P0052', category: 'P', description: 'HO2S Heater Control Circuit High Bank 2 Sensor 1' },
  { code: 'P0053', category: 'P', description: 'HO2S Heater Resistance Bank 1 Sensor 1' },
  { code: 'P0054', category: 'P', description: 'HO2S Heater Resistance Bank 1 Sensor 2' },
  { code: 'P0055', category: 'P', description: 'HO2S Heater Resistance Bank 1 Sensor 3' },
  { code: 'P0056', category: 'P', description: 'HO2S Heater Control Circuit Bank 2 Sensor 2' },
  { code: 'P0057', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 2 Sensor 2' },
  { code: 'P0058', category: 'P', description: 'HO2S Heater Control Circuit High Bank 2 Sensor 2' },
  { code: 'P0059', category: 'P', description: 'HO2S Heater Resistance Bank 2 Sensor 1' },
  { code: 'P0060', category: 'P', description: 'HO2S Heater Resistance Bank 2 Sensor 2' },
  { code: 'P0061', category: 'P', description: 'HO2S Heater Resistance Bank 2 Sensor 3' },
  { code: 'P0062', category: 'P', description: 'HO2S Heater Control Circuit Bank 2 Sensor 3' },
  { code: 'P0063', category: 'P', description: 'HO2S Heater Control Circuit Low Bank 2 Sensor 3' },
  { code: 'P0064', category: 'P', description: 'HO2S Heater Control Circuit High Bank 2 Sensor 3' },
  { code: 'P0065', category: 'P', description: 'Air Assisted Injector Control Range/Performance' },
  { code: 'P0066', category: 'P', description: 'Air Assisted Injector Control Circuit Low' },
  { code: 'P0067', category: 'P', description: 'Air Assisted Injector Control Circuit High' },
  { code: 'P0068', category: 'P', description: 'MAP/MAF - Throttle Position Correlation' },
  { code: 'P0069', category: 'P', description: 'Manifold Absolute Pressure - Barometric Pressure Correlation' },
  { code: 'P0070', category: 'P', description: 'Ambient Air Temperature Sensor Circuit A' },
  { code: 'P0071', category: 'P', description: 'Ambient Air Temperature Sensor Circuit A Range/Performance' },
  { code: 'P0072', category: 'P', description: 'Ambient Air Temperature Sensor Circuit A Low' },
  { code: 'P0073', category: 'P', description: 'Ambient Air Temperature Sensor Circuit A High' },
  { code: 'P0074', category: 'P', description: 'Ambient Air Temperature Sensor Circuit A Intermittent/Erratic' },
  { code: 'P0075', category: 'P', description: 'Intake Valve Control Solenoid Circuit Bank 1' },
  { code: 'P0076', category: 'P', description: 'Intake Valve Control Solenoid Circuit Low Bank 1' },
  { code: 'P0077', category: 'P', description: 'Intake Valve Control Solenoid Circuit High Bank 1' },
  { code: 'P0078', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Bank 1' },
  { code: 'P0079', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Low Bank 1' },
  { code: 'P0080', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit High Bank 1' },
  { code: 'P0081', category: 'P', description: 'Intake Valve Control Solenoid Circuit Bank 2' },
  { code: 'P0082', category: 'P', description: 'Intake Valve Control Solenoid Circuit Low Bank 2' },
  { code: 'P0083', category: 'P', description: 'Intake Valve Control Solenoid Circuit High Bank 2' },
  { code: 'P0084', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Bank 2' },
  { code: 'P0085', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit Low Bank 2' },
  { code: 'P0086', category: 'P', description: 'Exhaust Valve Control Solenoid Circuit High Bank 2' },
  { code: 'P0087', category: 'P', description: 'Fuel Rail/System Pressure - Too Low Bank 1' },
  { code: 'P0088', category: 'P', description: 'Fuel Rail/System Pressure - Too High Bank 1' },
  { code: 'P0089', category: 'P', description: 'Fuel Pressure Regulator A Performance' },
  { code: 'P0090', category: 'P', description: 'Fuel Pressure Regulator A Control Circuit/Open' },
  { code: 'P0091', category: 'P', description: 'Fuel Pressure Regulator A Control Circuit Low' },
  { code: 'P0092', category: 'P', description: 'Fuel Pressure Regulator A Control Circuit High' },
  { code: 'P0093', category: 'P', description: 'Fuel System Leak Detected - Large Leak' },
  { code: 'P0094', category: 'P', description: 'Fuel System Leak Detected - Small Leak' },
  { code: 'P0095', category: 'P', description: 'Intake Air Temperature Sensor 2 Circuit Bank 1' },
  { code: 'P0096', category: 'P', description: 'Intake Air Temperature Sensor 2 Circuit Range/Performance Bank 1' },
  { code: 'P0097', category: 'P', description: 'Intake Air Temperature Sensor 2 Circuit Low Bank 1' },
  { code: 'P0098', category: 'P', description: 'Intake Air Temperature Sensor 2 Circuit High Bank 1' },
  { code: 'P0099', category: 'P', description: 'Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic Bank 1' },

  // ── P0100–P0199: Fuel & Air Metering ──────────────────────────────────
  { code: 'P0100', category: 'P', description: 'Mass or Volume Air Flow Sensor A Circuit' },
  { code: 'P0101', category: 'P', description: 'Mass or Volume Air Flow Sensor A Circuit Range/Performance' },
  { code: 'P0102', category: 'P', description: 'Mass or Volume Air Flow Sensor A Circuit Low' },
  { code: 'P0103', category: 'P', description: 'Mass or Volume Air Flow Sensor A Circuit High' },
  { code: 'P0104', category: 'P', description: 'Mass or Volume Air Flow Sensor A Circuit Intermittent' },
  { code: 'P0105', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Sensor Circuit' },
  { code: 'P0106', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Sensor Circuit Range/Performance' },
  { code: 'P0107', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Sensor Circuit Low' },
  { code: 'P0108', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Sensor Circuit High' },
  { code: 'P0109', category: 'P', description: 'Manifold Absolute Pressure/Barometric Pressure Sensor Circuit Intermittent' },
  { code: 'P0110', category: 'P', description: 'Intake Air Temperature Sensor 1 Circuit Bank 1' },
  { code: 'P0111', category: 'P', description: 'Intake Air Temperature Sensor 1 Circuit Range/Performance Bank 1' },
  { code: 'P0112', category: 'P', description: 'Intake Air Temperature Sensor 1 Circuit Low Bank 1' },
  { code: 'P0113', category: 'P', description: 'Intake Air Temperature Sensor 1 Circuit High Bank 1' },
  { code: 'P0114', category: 'P', description: 'Intake Air Temperature Sensor 1 Circuit Intermittent Bank 1' },
  { code: 'P0115', category: 'P', description: 'Engine Coolant Temperature Sensor 1 Circuit' },
  { code: 'P0116', category: 'P', description: 'Engine Coolant Temperature Sensor 1 Circuit Range/Performance' },
  { code: 'P0117', category: 'P', description: 'Engine Coolant Temperature Sensor 1 Circuit Low' },
  { code: 'P0118', category: 'P', description: 'Engine Coolant Temperature Sensor 1 Circuit High' },
  { code: 'P0119', category: 'P', description: 'Engine Coolant Temperature Sensor 1 Circuit Intermittent/Erratic' },
  { code: 'P0120', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch A Circuit' },
  { code: 'P0121', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance' },
  { code: 'P0122', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch A Circuit Low' },
  { code: 'P0123', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch A Circuit High' },
  { code: 'P0124', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch A Circuit Intermittent' },
  { code: 'P0125', category: 'P', description: 'Insufficient Coolant Temperature for Closed Loop Fuel Control' },
  { code: 'P0126', category: 'P', description: 'Insufficient Coolant Temperature for Stable Operation' },
  { code: 'P0127', category: 'P', description: 'Intake Air Temperature Too High' },
  { code: 'P0128', category: 'P', description: 'Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)' },
  { code: 'P0129', category: 'P', description: 'Barometric Pressure Too Low' },
  { code: 'P0130', category: 'P', description: 'O2 Sensor Circuit Bank 1 Sensor 1' },
  { code: 'P0131', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 1 Sensor 1' },
  { code: 'P0132', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 1 Sensor 1' },
  { code: 'P0133', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 1 Sensor 1' },
  { code: 'P0134', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 1 Sensor 1' },
  { code: 'P0135', category: 'P', description: 'O2 Sensor Heater Circuit Bank 1 Sensor 1' },
  { code: 'P0136', category: 'P', description: 'O2 Sensor Circuit Bank 1 Sensor 2' },
  { code: 'P0137', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 1 Sensor 2' },
  { code: 'P0138', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 1 Sensor 2' },
  { code: 'P0139', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 1 Sensor 2' },
  { code: 'P0140', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 1 Sensor 2' },
  { code: 'P0141', category: 'P', description: 'O2 Sensor Heater Circuit Bank 1 Sensor 2' },
  { code: 'P0142', category: 'P', description: 'O2 Sensor Circuit Bank 1 Sensor 3' },
  { code: 'P0143', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 1 Sensor 3' },
  { code: 'P0144', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 1 Sensor 3' },
  { code: 'P0145', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 1 Sensor 3' },
  { code: 'P0146', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 1 Sensor 3' },
  { code: 'P0147', category: 'P', description: 'O2 Sensor Heater Circuit Bank 1 Sensor 3' },
  { code: 'P0148', category: 'P', description: 'Fuel Delivery Error' },
  { code: 'P0149', category: 'P', description: 'Fuel Timing Error' },
  { code: 'P0150', category: 'P', description: 'O2 Sensor Circuit Bank 2 Sensor 1' },
  { code: 'P0151', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 2 Sensor 1' },
  { code: 'P0152', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 2 Sensor 1' },
  { code: 'P0153', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 2 Sensor 1' },
  { code: 'P0154', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 2 Sensor 1' },
  { code: 'P0155', category: 'P', description: 'O2 Sensor Heater Circuit Bank 2 Sensor 1' },
  { code: 'P0156', category: 'P', description: 'O2 Sensor Circuit Bank 2 Sensor 2' },
  { code: 'P0157', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 2 Sensor 2' },
  { code: 'P0158', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 2 Sensor 2' },
  { code: 'P0159', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 2 Sensor 2' },
  { code: 'P0160', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 2 Sensor 2' },
  { code: 'P0161', category: 'P', description: 'O2 Sensor Heater Circuit Bank 2 Sensor 2' },
  { code: 'P0162', category: 'P', description: 'O2 Sensor Circuit Bank 2 Sensor 3' },
  { code: 'P0163', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 2 Sensor 3' },
  { code: 'P0164', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 2 Sensor 3' },
  { code: 'P0165', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 2 Sensor 3' },
  { code: 'P0166', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 2 Sensor 3' },
  { code: 'P0167', category: 'P', description: 'O2 Sensor Heater Circuit Bank 2 Sensor 3' },
  { code: 'P0168', category: 'P', description: 'Fuel Temperature Too High' },
  { code: 'P0169', category: 'P', description: 'Incorrect Fuel Composition' },
  { code: 'P0170', category: 'P', description: 'Fuel Trim Bank 1' },
  { code: 'P0171', category: 'P', description: 'System Too Lean Bank 1' },
  { code: 'P0172', category: 'P', description: 'System Too Rich Bank 1' },
  { code: 'P0173', category: 'P', description: 'Fuel Trim Bank 2' },
  { code: 'P0174', category: 'P', description: 'System Too Lean Bank 2' },
  { code: 'P0175', category: 'P', description: 'System Too Rich Bank 2' },
  { code: 'P0176', category: 'P', description: 'Fuel Composition Sensor Circuit' },
  { code: 'P0177', category: 'P', description: 'Fuel Composition Sensor Circuit Range/Performance' },
  { code: 'P0178', category: 'P', description: 'Fuel Composition Sensor Circuit Low' },
  { code: 'P0179', category: 'P', description: 'Fuel Composition Sensor Circuit High' },
  { code: 'P0180', category: 'P', description: 'Fuel Temperature Sensor A Circuit' },
  { code: 'P0181', category: 'P', description: 'Fuel Temperature Sensor A Circuit Range/Performance' },
  { code: 'P0182', category: 'P', description: 'Fuel Temperature Sensor A Circuit Low' },
  { code: 'P0183', category: 'P', description: 'Fuel Temperature Sensor A Circuit High' },
  { code: 'P0184', category: 'P', description: 'Fuel Temperature Sensor A Circuit Intermittent' },
  { code: 'P0185', category: 'P', description: 'Fuel Temperature Sensor B Circuit' },
  { code: 'P0186', category: 'P', description: 'Fuel Temperature Sensor B Circuit Range/Performance' },
  { code: 'P0187', category: 'P', description: 'Fuel Temperature Sensor B Circuit Low' },
  { code: 'P0188', category: 'P', description: 'Fuel Temperature Sensor B Circuit High' },
  { code: 'P0189', category: 'P', description: 'Fuel Temperature Sensor B Circuit Intermittent' },
  { code: 'P0190', category: 'P', description: 'Fuel Rail Pressure Sensor Circuit Bank 1' },
  { code: 'P0191', category: 'P', description: 'Fuel Rail Pressure Sensor Circuit Range/Performance Bank 1' },
  { code: 'P0192', category: 'P', description: 'Fuel Rail Pressure Sensor Circuit Low Bank 1' },
  { code: 'P0193', category: 'P', description: 'Fuel Rail Pressure Sensor Circuit High Bank 1' },
  { code: 'P0194', category: 'P', description: 'Fuel Rail Pressure Sensor Circuit Intermittent/Erratic Bank 1' },
  { code: 'P0195', category: 'P', description: 'Engine Oil Temperature Sensor A Circuit' },
  { code: 'P0196', category: 'P', description: 'Engine Oil Temperature Sensor A Range/Performance' },
  { code: 'P0197', category: 'P', description: 'Engine Oil Temperature Sensor A Circuit Low' },
  { code: 'P0198', category: 'P', description: 'Engine Oil Temperature Sensor A Circuit High' },
  { code: 'P0199', category: 'P', description: 'Engine Oil Temperature Sensor A Circuit Intermittent/Erratic' },

  // ── P0200–P0299: Fuel & Air Metering — Injector Circuit ──────────────
  { code: 'P0200', category: 'P', description: 'Fuel Injector Circuit' },
  { code: 'P0201', category: 'P', description: 'Fuel Injector Circuit Cylinder 1' },
  { code: 'P0202', category: 'P', description: 'Fuel Injector Circuit Cylinder 2' },
  { code: 'P0203', category: 'P', description: 'Fuel Injector Circuit Cylinder 3' },
  { code: 'P0204', category: 'P', description: 'Fuel Injector Circuit Cylinder 4' },
  { code: 'P0205', category: 'P', description: 'Fuel Injector Circuit Cylinder 5' },
  { code: 'P0206', category: 'P', description: 'Fuel Injector Circuit Cylinder 6' },
  { code: 'P0207', category: 'P', description: 'Fuel Injector Circuit Cylinder 7' },
  { code: 'P0208', category: 'P', description: 'Fuel Injector Circuit Cylinder 8' },
  { code: 'P0209', category: 'P', description: 'Fuel Injector Circuit Cylinder 9' },
  { code: 'P0210', category: 'P', description: 'Fuel Injector Circuit Cylinder 10' },
  { code: 'P0211', category: 'P', description: 'Fuel System Injector X Timing' },
  { code: 'P0212', category: 'P', description: 'Fuel Injector Pulsewidth Bank 1' },
  { code: 'P0213', category: 'P', description: 'Cold Start Fuel Injector' },
  { code: 'P0214', category: 'P', description: 'Fuel Injector Air Bleed Solenoid' },
  { code: 'P0215', category: 'P', description: 'Engine Shutoff Solenoid' },
  { code: 'P0216', category: 'P', description: 'Injection Pump Timing' },
  { code: 'P0217', category: 'P', description: 'Engine Over Temperature Condition' },
  { code: 'P0218', category: 'P', description: 'Transmission Over Temperature' },
  { code: 'P0219', category: 'P', description: 'Engine Over Speed Condition' },
  { code: 'P0220', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch B Circuit' },
  { code: 'P0221', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance' },
  { code: 'P0222', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch B Circuit Low' },
  { code: 'P0223', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch B Circuit High' },
  { code: 'P0224', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch B Circuit Intermittent' },
  { code: 'P0225', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch C Circuit' },
  { code: 'P0226', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch C Circuit Range/Performance' },
  { code: 'P0227', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch C Circuit Low' },
  { code: 'P0228', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch C Circuit High' },
  { code: 'P0229', category: 'P', description: 'Throttle/Pedal Position Sensor/Switch C Circuit Intermittent' },
  { code: 'P0230', category: 'P', description: 'Fuel Pump Primary Circuit' },
  { code: 'P0231', category: 'P', description: 'Fuel Pump Secondary Circuit Low' },
  { code: 'P0232', category: 'P', description: 'Fuel Pump Secondary Circuit High' },
  { code: 'P0233', category: 'P', description: 'Fuel Pump Secondary Circuit Intermittent' },
  { code: 'P0234', category: 'P', description: 'Engine Over Boost Condition' },
  { code: 'P0235', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor A Circuit' },
  { code: 'P0236', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor A Circuit Range/Performance' },
  { code: 'P0237', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor A Circuit Low' },
  { code: 'P0238', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor A Circuit High' },
  { code: 'P0239', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor B Circuit' },
  { code: 'P0240', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor B Circuit Range/Performance' },
  { code: 'P0241', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor B Circuit Low' },
  { code: 'P0242', category: 'P', description: 'Turbocharger/Supercharger Boost Sensor B Circuit High' },
  { code: 'P0243', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid A' },
  { code: 'P0244', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid A Low' },
  { code: 'P0245', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid A High' },
  { code: 'P0246', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid B' },
  { code: 'P0247', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid B Low' },
  { code: 'P0248', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid B High' },
  { code: 'P0249', category: 'P', description: 'Turbocharger/Supercharger Wastegate Solenoid B Range/Performance' },
  { code: 'P0250', category: 'P', description: 'Engine Speed Governor Load Increase' },
  { code: 'P0251', category: 'P', description: 'Injection Pump Fuel Metering Control A' },
  { code: 'P0252', category: 'P', description: 'Injection Pump Fuel Metering Control Range/Performance A' },
  { code: 'P0253', category: 'P', description: 'Injection Pump Fuel Metering Control Low A' },
  { code: 'P0254', category: 'P', description: 'Injection Pump Fuel Metering Control High A' },
  { code: 'P0255', category: 'P', description: 'Injection Pump Fuel Metering Control Intermittent A' },
  { code: 'P0256', category: 'P', description: 'Injection Pump Fuel Metering Control B' },
  { code: 'P0257', category: 'P', description: 'Injection Pump Fuel Metering Control Range/Performance B' },
  { code: 'P0258', category: 'P', description: 'Injection Pump Fuel Metering Control Low B' },
  { code: 'P0259', category: 'P', description: 'Injection Pump Fuel Metering Control High B' },
  { code: 'P0260', category: 'P', description: 'Injection Pump Fuel Metering Control Intermittent B' },
  { code: 'P0261', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 1' },
  { code: 'P0262', category: 'P', description: 'Fuel Injector Circuit High Cylinder 1' },
  { code: 'P0263', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 1' },
  { code: 'P0264', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 2' },
  { code: 'P0265', category: 'P', description: 'Fuel Injector Circuit High Cylinder 2' },
  { code: 'P0266', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 2' },
  { code: 'P0267', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 3' },
  { code: 'P0268', category: 'P', description: 'Fuel Injector Circuit High Cylinder 3' },
  { code: 'P0269', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 3' },
  { code: 'P0270', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 4' },
  { code: 'P0271', category: 'P', description: 'Fuel Injector Circuit High Cylinder 4' },
  { code: 'P0272', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 4' },
  { code: 'P0273', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 5' },
  { code: 'P0274', category: 'P', description: 'Fuel Injector Circuit High Cylinder 5' },
  { code: 'P0275', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 5' },
  { code: 'P0276', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 6' },
  { code: 'P0277', category: 'P', description: 'Fuel Injector Circuit High Cylinder 6' },
  { code: 'P0278', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 6' },
  { code: 'P0279', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 7' },
  { code: 'P0280', category: 'P', description: 'Fuel Injector Circuit High Cylinder 7' },
  { code: 'P0281', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 7' },
  { code: 'P0282', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 8' },
  { code: 'P0283', category: 'P', description: 'Fuel Injector Circuit High Cylinder 8' },
  { code: 'P0284', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 8' },
  { code: 'P0285', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 9' },
  { code: 'P0286', category: 'P', description: 'Fuel Injector Circuit High Cylinder 9' },
  { code: 'P0287', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 9' },
  { code: 'P0288', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 10' },
  { code: 'P0289', category: 'P', description: 'Fuel Injector Circuit High Cylinder 10' },
  { code: 'P0290', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 10' },
  { code: 'P0291', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 11' },
  { code: 'P0292', category: 'P', description: 'Fuel Injector Circuit High Cylinder 11' },
  { code: 'P0293', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 11' },
  { code: 'P0294', category: 'P', description: 'Fuel Injector Circuit Low Cylinder 12' },
  { code: 'P0295', category: 'P', description: 'Fuel Injector Circuit High Cylinder 12' },
  { code: 'P0296', category: 'P', description: 'Fuel Injector Circuit Intermittent Cylinder 12' },
  { code: 'P0297', category: 'P', description: 'Vehicle Speed Governor Fault' },
  { code: 'P0298', category: 'P', description: 'Engine Oil Over Temperature' },
  { code: 'P0299', category: 'P', description: 'Turbocharger/Supercharger Underboost' },

  // ── P0300–P0399: Ignition System / Misfire ────────────────────────────
  { code: 'P0300', category: 'P', description: 'Random/Multiple Cylinder Misfire Detected' },
  { code: 'P0301', category: 'P', description: 'Cylinder 1 Misfire Detected' },
  { code: 'P0302', category: 'P', description: 'Cylinder 2 Misfire Detected' },
  { code: 'P0303', category: 'P', description: 'Cylinder 3 Misfire Detected' },
  { code: 'P0304', category: 'P', description: 'Cylinder 4 Misfire Detected' },
  { code: 'P0305', category: 'P', description: 'Cylinder 5 Misfire Detected' },
  { code: 'P0306', category: 'P', description: 'Cylinder 6 Misfire Detected' },
  { code: 'P0307', category: 'P', description: 'Cylinder 7 Misfire Detected' },
  { code: 'P0308', category: 'P', description: 'Cylinder 8 Misfire Detected' },
  { code: 'P0309', category: 'P', description: 'Cylinder 9 Misfire Detected' },
  { code: 'P0310', category: 'P', description: 'Cylinder 10 Misfire Detected' },
  { code: 'P0311', category: 'P', description: 'Cylinder 11 Misfire Detected' },
  { code: 'P0312', category: 'P', description: 'Cylinder 12 Misfire Detected' },
  { code: 'P0313', category: 'P', description: 'Misfire Detected with Low Fuel' },
  { code: 'P0314', category: 'P', description: 'Single Cylinder Misfire' },
  { code: 'P0315', category: 'P', description: 'Crankshaft Position System Not Learned' },
  { code: 'P0316', category: 'P', description: 'Engine Misfire Detected on Startup' },
  { code: 'P0317', category: 'P', description: 'Misfire Detected - Rough Road' },
  { code: 'P0318', category: 'P', description: 'Knock Sensor 1 - 2 Correlation' },
  { code: 'P0319', category: 'P', description: 'Misfire Detected - Idle Only' },
  { code: 'P0320', category: 'P', description: 'Ignition/Distributor Engine Speed Input Circuit' },
  { code: 'P0321', category: 'P', description: 'Ignition/Distributor Engine Speed Input Circuit Range/Performance' },
  { code: 'P0322', category: 'P', description: 'Ignition/Distributor Engine Speed Input Circuit No Signal' },
  { code: 'P0323', category: 'P', description: 'Ignition/Distributor Engine Speed Input Circuit Intermittent' },
  { code: 'P0324', category: 'P', description: 'Knock Control System Error' },
  { code: 'P0325', category: 'P', description: 'Knock Sensor 1 Circuit Bank 1 or Single Sensor' },
  { code: 'P0326', category: 'P', description: 'Knock Sensor 1 Circuit Range/Performance Bank 1 or Single Sensor' },
  { code: 'P0327', category: 'P', description: 'Knock Sensor 1 Circuit Low Bank 1 or Single Sensor' },
  { code: 'P0328', category: 'P', description: 'Knock Sensor 1 Circuit High Bank 1 or Single Sensor' },
  { code: 'P0329', category: 'P', description: 'Knock Sensor 1 Circuit Intermittent Bank 1 or Single Sensor' },
  { code: 'P0330', category: 'P', description: 'Knock Sensor 2 Circuit Bank 2' },
  { code: 'P0331', category: 'P', description: 'Knock Sensor 2 Circuit Range/Performance Bank 2' },
  { code: 'P0332', category: 'P', description: 'Knock Sensor 2 Circuit Low Bank 2' },
  { code: 'P0333', category: 'P', description: 'Knock Sensor 2 Circuit High Bank 2' },
  { code: 'P0334', category: 'P', description: 'Knock Sensor 2 Circuit Intermittent Bank 2' },
  { code: 'P0335', category: 'P', description: 'Crankshaft Position Sensor A Circuit' },
  { code: 'P0336', category: 'P', description: 'Crankshaft Position Sensor A Circuit Range/Performance' },
  { code: 'P0337', category: 'P', description: 'Crankshaft Position Sensor A Circuit Low' },
  { code: 'P0338', category: 'P', description: 'Crankshaft Position Sensor A Circuit High' },
  { code: 'P0339', category: 'P', description: 'Crankshaft Position Sensor A Circuit Intermittent' },
  { code: 'P0340', category: 'P', description: 'Camshaft Position Sensor A Circuit Bank 1 or Single Sensor' },
  { code: 'P0341', category: 'P', description: 'Camshaft Position Sensor A Circuit Range/Performance Bank 1 or Single Sensor' },
  { code: 'P0342', category: 'P', description: 'Camshaft Position Sensor A Circuit Low Bank 1 or Single Sensor' },
  { code: 'P0343', category: 'P', description: 'Camshaft Position Sensor A Circuit High Bank 1 or Single Sensor' },
  { code: 'P0344', category: 'P', description: 'Camshaft Position Sensor A Circuit Intermittent Bank 1 or Single Sensor' },
  { code: 'P0345', category: 'P', description: 'Camshaft Position Sensor A Circuit Bank 2' },
  { code: 'P0346', category: 'P', description: 'Camshaft Position Sensor A Circuit Range/Performance Bank 2' },
  { code: 'P0347', category: 'P', description: 'Camshaft Position Sensor A Circuit Low Bank 2' },
  { code: 'P0348', category: 'P', description: 'Camshaft Position Sensor A Circuit High Bank 2' },
  { code: 'P0349', category: 'P', description: 'Camshaft Position Sensor A Circuit Intermittent Bank 2' },
  { code: 'P0350', category: 'P', description: 'Ignition Coil Primary/Secondary Circuit' },
  { code: 'P0351', category: 'P', description: 'Ignition Coil A Primary/Secondary Circuit' },
  { code: 'P0352', category: 'P', description: 'Ignition Coil B Primary/Secondary Circuit' },
  { code: 'P0353', category: 'P', description: 'Ignition Coil C Primary/Secondary Circuit' },
  { code: 'P0354', category: 'P', description: 'Ignition Coil D Primary/Secondary Circuit' },
  { code: 'P0355', category: 'P', description: 'Ignition Coil E Primary/Secondary Circuit' },
  { code: 'P0356', category: 'P', description: 'Ignition Coil F Primary/Secondary Circuit' },
  { code: 'P0357', category: 'P', description: 'Ignition Coil G Primary/Secondary Circuit' },
  { code: 'P0358', category: 'P', description: 'Ignition Coil H Primary/Secondary Circuit' },
  { code: 'P0359', category: 'P', description: 'Ignition Coil I Primary/Secondary Circuit' },
  { code: 'P0360', category: 'P', description: 'Ignition Coil J Primary/Secondary Circuit' },
  { code: 'P0361', category: 'P', description: 'Ignition Coil K Primary/Secondary Circuit' },
  { code: 'P0362', category: 'P', description: 'Ignition Coil L Primary/Secondary Circuit' },
  { code: 'P0363', category: 'P', description: 'Misfire Detected - Fueling Disabled' },
  { code: 'P0364', category: 'P', description: 'Misfire Detected - Ignition Timing Retarded' },
  { code: 'P0365', category: 'P', description: 'Camshaft Position Sensor B Circuit Bank 1 or Single Sensor' },
  { code: 'P0366', category: 'P', description: 'Camshaft Position Sensor B Circuit Range/Performance Bank 1 or Single Sensor' },
  { code: 'P0367', category: 'P', description: 'Camshaft Position Sensor B Circuit Low Bank 1 or Single Sensor' },
  { code: 'P0368', category: 'P', description: 'Camshaft Position Sensor B Circuit High Bank 1 or Single Sensor' },
  { code: 'P0369', category: 'P', description: 'Camshaft Position Sensor B Circuit Intermittent Bank 1 or Single Sensor' },
  { code: 'P0370', category: 'P', description: 'Timing Reference High Resolution Signal A' },
  { code: 'P0371', category: 'P', description: 'Timing Reference High Resolution Signal A Too Many Pulses' },
  { code: 'P0372', category: 'P', description: 'Timing Reference High Resolution Signal A Too Few Pulses' },
  { code: 'P0373', category: 'P', description: 'Timing Reference High Resolution Signal A Intermittent/Erratic Pulses' },
  { code: 'P0374', category: 'P', description: 'Timing Reference High Resolution Signal B Detected' },
  { code: 'P0375', category: 'P', description: 'Timing Reference High Resolution Signal B' },
  { code: 'P0376', category: 'P', description: 'Timing Reference High Resolution Signal B Too Many Pulses' },
  { code: 'P0377', category: 'P', description: 'Timing Reference High Resolution Signal B Too Few Pulses' },
  { code: 'P0378', category: 'P', description: 'Timing Reference High Resolution Signal B Intermittent/Erratic Pulses' },
  { code: 'P0379', category: 'P', description: 'Timing Reference High Resolution Signal A/B Correlation' },
  { code: 'P0380', category: 'P', description: 'Glow Plug/Heater Circuit Bank 1' },
  { code: 'P0381', category: 'P', description: 'Glow Plug/Heater Indicator Lamp Control Circuit' },
  { code: 'P0382', category: 'P', description: 'Glow Plug/Heater Circuit Bank 2' },
  { code: 'P0383', category: 'P', description: 'High Beam Control Circuit' },
  { code: 'P0384', category: 'P', description: 'Low Beam Control Circuit' },
  { code: 'P0385', category: 'P', description: 'Crankshaft Position Sensor B Circuit' },
  { code: 'P0386', category: 'P', description: 'Crankshaft Position Sensor B Circuit Range/Performance' },
  { code: 'P0387', category: 'P', description: 'Crankshaft Position Sensor B Circuit Low' },
  { code: 'P0388', category: 'P', description: 'Crankshaft Position Sensor B Circuit High' },
  { code: 'P0389', category: 'P', description: 'Crankshaft Position Sensor B Circuit Intermittent' },
  { code: 'P0390', category: 'P', description: 'Camshaft Position Sensor B Circuit Bank 2' },
  { code: 'P0391', category: 'P', description: 'Camshaft Position Sensor B Circuit Range/Performance Bank 2' },
  { code: 'P0392', category: 'P', description: 'Camshaft Position Sensor B Circuit Low Bank 2' },
  { code: 'P0393', category: 'P', description: 'Camshaft Position Sensor B Circuit High Bank 2' },
  { code: 'P0394', category: 'P', description: 'Camshaft Position Sensor B Circuit Intermittent Bank 2' },
  { code: 'P0395', category: 'P', description: 'Crankshaft Position Sensor C Circuit' },
  { code: 'P0396', category: 'P', description: 'Crankshaft Position Sensor C Circuit Range/Performance' },
  { code: 'P0397', category: 'P', description: 'Crankshaft Position Sensor C Circuit Low' },
  { code: 'P0398', category: 'P', description: 'Crankshaft Position Sensor C Circuit High' },
  { code: 'P0399', category: 'P', description: 'Crankshaft Position Sensor C Circuit Intermittent' },

  // ── P0400–P0499: Emission Control ─────────────────────────────────────
  { code: 'P0400', category: 'P', description: 'EVAP System Flow' },
  { code: 'P0401', category: 'P', description: 'EGR System Flow Insufficient' },
  { code: 'P0402', category: 'P', description: 'EGR System Flow Excessive' },
  { code: 'P0403', category: 'P', description: 'EGR Control Circuit' },
  { code: 'P0404', category: 'P', description: 'EGR Control Circuit Range/Performance' },
  { code: 'P0405', category: 'P', description: 'EGR Sensor A Circuit Low' },
  { code: 'P0406', category: 'P', description: 'EGR Sensor A Circuit High' },
  { code: 'P0407', category: 'P', description: 'EGR Sensor B Circuit Low' },
  { code: 'P0408', category: 'P', description: 'EGR Sensor B Circuit High' },
  { code: 'P0409', category: 'P', description: 'EGR Sensor A Circuit Intermittent' },
  { code: 'P0410', category: 'P', description: 'Secondary Air Injection System' },
  { code: 'P0411', category: 'P', description: 'Secondary Air Injection System Incorrect Flow Detected' },
  { code: 'P0412', category: 'P', description: 'Secondary Air Injection Control Valve A Circuit' },
  { code: 'P0413', category: 'P', description: 'Secondary Air Injection Control Valve A Circuit Open' },
  { code: 'P0414', category: 'P', description: 'Secondary Air Injection Control Valve A Circuit Shorted' },
  { code: 'P0415', category: 'P', description: 'Secondary Air Injection Control Valve B Circuit' },
  { code: 'P0416', category: 'P', description: 'Secondary Air Injection Control Valve B Circuit Open' },
  { code: 'P0417', category: 'P', description: 'Secondary Air Injection Control Valve B Circuit Shorted' },
  { code: 'P0418', category: 'P', description: 'Secondary Air Injection Pump Control Circuit' },
  { code: 'P0419', category: 'P', description: 'Secondary Air Injection Pump Control Circuit B' },
  { code: 'P0420', category: 'P', description: 'Catalyst System Efficiency Below Threshold Bank 1' },
  { code: 'P0421', category: 'P', description: 'Warm Up Catalyst Efficiency Below Threshold Bank 1' },
  { code: 'P0422', category: 'P', description: 'Main Catalyst Efficiency Below Threshold Bank 1' },
  { code: 'P0423', category: 'P', description: 'Heated Catalyst Efficiency Below Threshold Bank 1' },
  { code: 'P0424', category: 'P', description: 'Catalyst Temperature Below Threshold Bank 1' },
  { code: 'P0425', category: 'P', description: 'Catalyst Temperature Above Threshold Bank 1' },
  { code: 'P0426', category: 'P', description: 'Catalyst Temperature Below Threshold Bank 2' },
  { code: 'P0427', category: 'P', description: 'Catalyst Temperature Above Threshold Bank 2' },
  { code: 'P0428', category: 'P', description: 'EVAP Pump Module Control Circuit' },
  { code: 'P0429', category: 'P', description: 'Secondary Air Injection Pump Control Circuit B' },
  { code: 'P0430', category: 'P', description: 'Catalyst System Efficiency Below Threshold Bank 2' },
  { code: 'P0431', category: 'P', description: 'Warm Up Catalyst Efficiency Below Threshold Bank 2' },
  { code: 'P0432', category: 'P', description: 'Main Catalyst Efficiency Below Threshold Bank 2' },
  { code: 'P0433', category: 'P', description: 'Heated Catalyst Efficiency Below Threshold Bank 2' },
  { code: 'P0434', category: 'P', description: 'Catalyst Monitor Performance Bank 2' },
  { code: 'P0435', category: 'P', description: 'O2 Sensor Circuit Bank 1 Sensor 4' },
  { code: 'P0436', category: 'P', description: 'O2 Sensor Circuit Low Voltage Bank 1 Sensor 4' },
  { code: 'P0437', category: 'P', description: 'O2 Sensor Circuit High Voltage Bank 1 Sensor 4' },
  { code: 'P0438', category: 'P', description: 'O2 Sensor Circuit Slow Response Bank 1 Sensor 4' },
  { code: 'P0439', category: 'P', description: 'O2 Sensor Circuit No Activity Detected Bank 1 Sensor 4' },
  { code: 'P0440', category: 'P', description: 'EVAP System' },
  { code: 'P0441', category: 'P', description: 'EVAP System Incorrect Purge Flow' },
  { code: 'P0442', category: 'P', description: 'EVAP System Leak Detected (Small Leak)' },
  { code: 'P0443', category: 'P', description: 'EVAP Purge Control Valve Circuit' },
  { code: 'P0444', category: 'P', description: 'EVAP Purge Control Valve Circuit Open' },
  { code: 'P0445', category: 'P', description: 'EVAP Purge Control Valve Circuit Shorted' },
  { code: 'P0446', category: 'P', description: 'EVAP Vent Control Circuit' },
  { code: 'P0447', category: 'P', description: 'EVAP Vent Control Circuit Open' },
  { code: 'P0448', category: 'P', description: 'EVAP Vent Control Circuit Shorted' },
  { code: 'P0449', category: 'P', description: 'EVAP Purge Valve Control Circuit' },
  { code: 'P0450', category: 'P', description: 'EVAP System Pressure Sensor' },
  { code: 'P0451', category: 'P', description: 'EVAP System Pressure Sensor Range/Performance' },
  { code: 'P0452', category: 'P', description: 'EVAP System Pressure Sensor Low' },
  { code: 'P0453', category: 'P', description: 'EVAP System Pressure Sensor High' },
  { code: 'P0454', category: 'P', description: 'EVAP System Pressure Sensor Intermittent' },
  { code: 'P0455', category: 'P', description: 'EVAP System Leak Detected (Large Leak)' },
  { code: 'P0456', category: 'P', description: 'EVAP System Leak Detected (Very Small Leak)' },
  { code: 'P0457', category: 'P', description: 'EVAP System Leak Detected (Fuel Cap Loose/Off)' },
  { code: 'P0458', category: 'P', description: 'EVAP Purge Control Valve Circuit Low' },
  { code: 'P0459', category: 'P', description: 'EVAP Purge Control Valve Circuit High' },
  { code: 'P0460', category: 'P', description: 'Fuel Level Sensor A Circuit' },
  { code: 'P0461', category: 'P', description: 'Fuel Level Sensor A Circuit Range/Performance' },
  { code: 'P0462', category: 'P', description: 'Fuel Level Sensor A Circuit Low' },
  { code: 'P0463', category: 'P', description: 'Fuel Level Sensor A Circuit High' },
  { code: 'P0464', category: 'P', description: 'Fuel Level Sensor A Circuit Intermittent' },
  { code: 'P0465', category: 'P', description: 'EVAP Vent Control Circuit Low' },
  { code: 'P0466', category: 'P', description: 'EVAP Vent Control Circuit High' },
  { code: 'P0467', category: 'P', description: 'EVAP Vent Control Solenoid A Circuit Low' },
  { code: 'P0468', category: 'P', description: 'EVAP Vent Control Solenoid A Circuit High' },
  { code: 'P0469', category: 'P', description: 'EVAP Purge Solenoid Control Circuit Low' },
  { code: 'P0470', category: 'P', description: 'Exhaust Pressure Sensor Circuit' },
  { code: 'P0471', category: 'P', description: 'Exhaust Pressure Sensor Circuit Range/Performance' },
  { code: 'P0472', category: 'P', description: 'Exhaust Pressure Sensor Circuit Low' },
  { code: 'P0473', category: 'P', description: 'Exhaust Pressure Sensor Circuit High' },
  { code: 'P0474', category: 'P', description: 'Exhaust Pressure Sensor Circuit Intermittent' },
  { code: 'P0475', category: 'P', description: 'Exhaust Pressure Control Valve' },
  { code: 'P0476', category: 'P', description: 'Exhaust Pressure Control Valve Range/Performance' },
  { code: 'P0477', category: 'P', description: 'Exhaust Pressure Control Valve Low' },
  { code: 'P0478', category: 'P', description: 'Exhaust Pressure Control Valve High' },
  { code: 'P0479', category: 'P', description: 'Exhaust Pressure Control Valve Intermittent' },
  { code: 'P0480', category: 'P', description: 'Cooling Fan 1 Control Circuit' },
  { code: 'P0481', category: 'P', description: 'Cooling Fan 2 Control Circuit' },
  { code: 'P0482', category: 'P', description: 'Cooling Fan 3 Control Circuit' },
  { code: 'P0483', category: 'P', description: 'Cooling Fan Rationality Check' },
  { code: 'P0484', category: 'P', description: 'Cooling Fan Circuit Over Temperature' },
  { code: 'P0485', category: 'P', description: 'Cooling Fan Power/Ground Circuit' },
  { code: 'P0486', category: 'P', description: 'EGR Lift Pump Control Circuit' },
  { code: 'P0487', category: 'P', description: 'EGR Throttle Position Control Circuit' },
  { code: 'P0488', category: 'P', description: 'EGR Throttle Position Control Exceeded' },
  { code: 'P0489', category: 'P', description: 'EGR Control Circuit Low' },
  { code: 'P0490', category: 'P', description: 'EGR Control Circuit High' },
  { code: 'P0491', category: 'P', description: 'Secondary Air Injection System Incorrect Flow Detected Bank 1' },
  { code: 'P0492', category: 'P', description: 'Secondary Air Injection System Incorrect Flow Detected Bank 2' },
  { code: 'P0493', category: 'P', description: 'Cooling Fan Over Current' },
  { code: 'P0494', category: 'P', description: 'Cooling Fan Rationality Check RPM too Low' },
  { code: 'P0495', category: 'P', description: 'Cooling Fan Rationality Check RPM too High' },
  { code: 'P0496', category: 'P', description: 'EVAP System High Purge Flow' },
  { code: 'P0497', category: 'P', description: 'EVAP System Low Purge Flow' },
  { code: 'P0498', category: 'P', description: 'EVAP Vent Control Solenoid B Circuit Low' },
  { code: 'P0499', category: 'P', description: 'EVAP Vent Control Solenoid B Circuit High' },

  // ── P0500–P0599: Vehicle Speed / Idle Control ─────────────────────────
  { code: 'P0500', category: 'P', description: 'Vehicle Speed Sensor A' },
  { code: 'P0501', category: 'P', description: 'Vehicle Speed Sensor A Range/Performance' },
  { code: 'P0502', category: 'P', description: 'Vehicle Speed Sensor A Circuit Low' },
  { code: 'P0503', category: 'P', description: 'Vehicle Speed Sensor A Intermittent/Erratic' },
  { code: 'P0504', category: 'P', description: 'Brake Switch A/B Correlation' },
  { code: 'P0505', category: 'P', description: 'Idle Air Control System Malfunction' },
  { code: 'P0506', category: 'P', description: 'Idle Speed Control System RPM Lower Than Expected' },
  { code: 'P0507', category: 'P', description: 'Idle Speed Control System RPM Higher Than Expected' },
  { code: 'P0508', category: 'P', description: 'Idle Air Control System Low' },
  { code: 'P0509', category: 'P', description: 'Idle Air Control System High' },
  { code: 'P0510', category: 'P', description: 'Closed Throttle Position Switch' },
  { code: 'P0511', category: 'P', description: 'Idle Air Control System Circuit' },
  { code: 'P0512', category: 'P', description: 'Starter Request Circuit' },
  { code: 'P0513', category: 'P', description: 'Incorrect Immobilizer Key' },
  { code: 'P0514', category: 'P', description: 'Battery Temperature Sensor A Circuit Intermittent/Erratic' },
  { code: 'P0515', category: 'P', description: 'Battery Temperature Sensor A Circuit Out of Range Low' },
  { code: 'P0516', category: 'P', description: 'Battery Temperature Sensor A Circuit Out of Range High' },
  { code: 'P0517', category: 'P', description: 'Battery Temperature Too Cold For CVVT' },
  { code: 'P0518', category: 'P', description: 'Idle Air Control System Electrical' },
  { code: 'P0519', category: 'P', description: 'Idle Speed Control System Performance' },
  { code: 'P0520', category: 'P', description: 'Engine Oil Pressure Sensor A Circuit' },
  { code: 'P0521', category: 'P', description: 'Engine Oil Pressure Sensor A Circuit Range/Performance' },
  { code: 'P0522', category: 'P', description: 'Engine Oil Pressure Sensor A Circuit Low' },
  { code: 'P0523', category: 'P', description: 'Engine Oil Pressure Sensor A Circuit High' },
  { code: 'P0524', category: 'P', description: 'Engine Oil Pressure Too Low' },
  { code: 'P0525', category: 'P', description: 'Engine Oil Pressure Too High' },
  { code: 'P0526', category: 'P', description: 'Engine Coolant Temperature Sensor 2 Circuit' },
  { code: 'P0527', category: 'P', description: 'Engine Coolant Temperature Sensor 2 Circuit Range/Performance' },
  { code: 'P0528', category: 'P', description: 'Engine Coolant Temperature Sensor 2 Circuit Low' },
  { code: 'P0529', category: 'P', description: 'Engine Coolant Temperature Sensor 2 Circuit High' },
  { code: 'P0530', category: 'P', description: 'Refrigerant Temperature Sensor Circuit' },
  { code: 'P0531', category: 'P', description: 'Refrigerant Temperature Sensor Circuit Range/Performance' },
  { code: 'P0532', category: 'P', description: 'Refrigerant Temperature Sensor Circuit Low' },
  { code: 'P0533', category: 'P', description: 'Refrigerant Temperature Sensor Circuit High' },
  { code: 'P0534', category: 'P', description: 'Refrigerant Charge Loss' },
  { code: 'P0535', category: 'P', description: 'Air Conditioning Refrigerant Pressure Sensor Circuit' },
  { code: 'P0536', category: 'P', description: 'Air Conditioning Refrigerant Pressure Sensor Circuit Range/Performance' },
  { code: 'P0537', category: 'P', description: 'Air Conditioning Refrigerant Pressure Sensor Circuit Low' },
  { code: 'P0538', category: 'P', description: 'Air Conditioning Refrigerant Pressure Sensor Circuit High' },
  { code: 'P0539', category: 'P', description: 'Air Conditioning Evaporator Temperature Sensor Circuit' },
  { code: 'P0540', category: 'P', description: 'Air Conditioning Evaporator Temperature Sensor Circuit Range/Performance' },
  { code: 'P0541', category: 'P', description: 'Air Conditioning Evaporator Temperature Sensor Circuit Low' },
  { code: 'P0542', category: 'P', description: 'Air Conditioning Evaporator Temperature Sensor Circuit High' },
  { code: 'P0543', category: 'P', description: 'Fuel Temperature Sensor B Circuit Intermittent' },
  { code: 'P0544', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit Bank 1 Sensor 1' },
  { code: 'P0545', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit Low Bank 1 Sensor 1' },
  { code: 'P0546', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit High Bank 1 Sensor 1' },
  { code: 'P0547', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit Bank 1 Sensor 2' },
  { code: 'P0548', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit Low Bank 1 Sensor 2' },
  { code: 'P0549', category: 'P', description: 'Exhaust Gas Temperature Sensor Circuit High Bank 1 Sensor 2' },
  { code: 'P0550', category: 'P', description: 'Power Steering Pressure Sensor Circuit' },
  { code: 'P0551', category: 'P', description: 'Power Steering Pressure Sensor Circuit Range/Performance' },
  { code: 'P0552', category: 'P', description: 'Power Steering Pressure Sensor Circuit Low' },
  { code: 'P0553', category: 'P', description: 'Power Steering Pressure Sensor Circuit High' },
  { code: 'P0554', category: 'P', description: 'Power Steering Pressure Sensor Circuit Intermittent' },
  { code: 'P0555', category: 'P', description: 'Engine Position System Performance Bank 1 Sensor 1' },
  { code: 'P0556', category: 'P', description: 'Engine Position System Performance Bank 1 Sensor 2' },
  { code: 'P0557', category: 'P', description: 'Engine Position System Performance Bank 2 Sensor 1' },
  { code: 'P0558', category: 'P', description: 'Engine Position System Performance Bank 2 Sensor 2' },
  { code: 'P0559', category: 'P', description: 'Engine Position System Performance Bank 3 Sensor 1' },
  { code: 'P0560', category: 'P', description: 'System Voltage Unstable' },
  { code: 'P0561', category: 'P', description: 'System Voltage Unstable' },
  { code: 'P0562', category: 'P', description: 'System Voltage Low' },
  { code: 'P0563', category: 'P', description: 'System Voltage High' },
  { code: 'P0564', category: 'P', description: 'Cruise Control Multi-function Input A Circuit' },
  { code: 'P0565', category: 'P', description: 'Cruise Control On/Off Switch' },
  { code: 'P0566', category: 'P', description: 'Cruise Control Resume/Accel Switch' },
  { code: 'P0567', category: 'P', description: 'Cruise Control Resume/Accel Switch Low' },
  { code: 'P0568', category: 'P', description: 'Cruise Control Resume/Accel Switch High' },
  { code: 'P0569', category: 'P', description: 'Cruise Control Coast/Decel Switch' },
  { code: 'P0570', category: 'P', description: 'Cruise Control Coast/Decel Switch Low' },
  { code: 'P0571', category: 'P', description: 'Cruise Control Brake Switch' },
  { code: 'P0572', category: 'P', description: 'Cruise Control Brake Switch Low' },
  { code: 'P0573', category: 'P', description: 'Cruise Control Brake Switch High' },
  { code: 'P0574', category: 'P', description: 'Cruise Control System Stuck On' },
  { code: 'P0575', category: 'P', description: 'Cruise Control System Stuck Off' },
  { code: 'P0576', category: 'P', description: 'Cruise Control Input A Low' },
  { code: 'P0577', category: 'P', description: 'Cruise Control Input A High' },
  { code: 'P0578', category: 'P', description: 'Cruise Control Input A Intermittent' },
  { code: 'P0579', category: 'P', description: 'Cruise Control Input B Circuit' },
  { code: 'P0580', category: 'P', description: 'Cruise Control Input B Low' },
  { code: 'P0581', category: 'P', description: 'Cruise Control Input B High' },
  { code: 'P0582', category: 'P', description: 'Cruise Control Input B Intermittent' },
  { code: 'P0583', category: 'P', description: 'Cruise Control Multi-function Input B Circuit' },
  { code: 'P0584', category: 'P', description: 'Cruise Control Multi-function Input A/B Correlation' },
  { code: 'P0585', category: 'P', description: 'Cruise Control Output A Low' },
  { code: 'P0586', category: 'P', description: 'Cruise Control Output A High' },
  { code: 'P0587', category: 'P', description: 'Cruise Control Throttle Actuator Circuit Low' },
  { code: 'P0588', category: 'P', description: 'Cruise Control Throttle Actuator Circuit High' },
  { code: 'P0589', category: 'P', description: 'Cruise Control Throttle Actuator Circuit Intermittent' },
  { code: 'P0590', category: 'P', description: 'Cruise Control System Fault' },
  { code: 'P0591', category: 'P', description: 'Cruise Control Control Error' },
  { code: 'P0592', category: 'P', description: 'Cruise Control Output Control Fault' },
  { code: 'P0593', category: 'P', description: 'Cruise Control Output A Intermittent' },
  { code: 'P0594', category: 'P', description: 'Cruise Control Output B Low' },
  { code: 'P0595', category: 'P', description: 'Cruise Control Output B High' },
  { code: 'P0596', category: 'P', description: 'Cruise Control Output B Intermittent' },
  { code: 'P0597', category: 'P', description: 'Cruise Control Output C Low' },
  { code: 'P0598', category: 'P', description: 'Cruise Control Output C High' },
  { code: 'P0599', category: 'P', description: 'Cruise Control Output C Intermittent' },

  // ── P0600–P0699: Computer Output Circuit ──────────────────────────────
  { code: 'P0600', category: 'P', description: 'Serial Communication Link' },
  { code: 'P0601', category: 'P', description: 'Internal Control Module Memory Check Sum Error' },
  { code: 'P0602', category: 'P', description: 'Control Module Programming Error' },
  { code: 'P0603', category: 'P', description: 'Internal Control Module Keep Alive Memory' },
  { code: 'P0604', category: 'P', description: 'Internal Control Module Random Access Memory (RAM) Error' },
  { code: 'P0605', category: 'P', description: 'Internal Control Module Read Only Memory (ROM) Error' },
  { code: 'P0606', category: 'P', description: 'PCM/ECM/ECU Processor Fault' },
  { code: 'P0607', category: 'P', description: 'Control Module Performance' },
  { code: 'P0608', category: 'P', description: 'Control Module VSS Output A' },
  { code: 'P0609', category: 'P', description: 'Control Module VSS Output B' },
  { code: 'P0610', category: 'P', description: 'Control Module Check Sum Error' },
  { code: 'P0611', category: 'P', description: 'ICP Sensor Calibration Out Of Range' },
  { code: 'P0612', category: 'P', description: 'Control Module Programming Not Complete' },
  { code: 'P0613', category: 'P', description: 'Internal Transmission Control Module (TCM) Check Sum Error' },
  { code: 'P0614', category: 'P', description: 'TCM Linked to PCM Not Compatible' },
  { code: 'P0615', category: 'P', description: 'Starter Motor Circuit A' },
  { code: 'P0616', category: 'P', description: 'Starter Motor Circuit A Low' },
  { code: 'P0617', category: 'P', description: 'Starter Motor Circuit A High' },
  { code: 'P0618', category: 'P', description: 'Alternative Fuel Control Module Check Sum Error' },
  { code: 'P0619', category: 'P', description: 'Engine Control Module/Transmission Control Module Mismatch' },
  { code: 'P0620', category: 'P', description: 'Generator Control Circuit' },
  { code: 'P0621', category: 'P', description: 'Generator Lamp/Terminal L Control Circuit' },
  { code: 'P0622', category: 'P', description: 'Generator Field Terminal Control Circuit' },
  { code: 'P0623', category: 'P', description: 'Generator Load Input Circuit' },
  { code: 'P0624', category: 'P', description: 'Generator Monitor Test Circuit' },
  { code: 'P0625', category: 'P', description: 'Generator Field Terminal Circuit Low' },
  { code: 'P0626', category: 'P', description: 'Generator Field Terminal Circuit High' },
  { code: 'P0627', category: 'P', description: 'Fuel Pump Relay Control Circuit' },
  { code: 'P0628', category: 'P', description: 'Fuel Pump Control Circuit Low' },
  { code: 'P0629', category: 'P', description: 'Fuel Pump Control Circuit High' },
  { code: 'P0630', category: 'P', description: 'VIN Not Programmed or Mismatch' },
  { code: 'P0631', category: 'P', description: 'VIN Not Programmed or Mismatch Mass Air Flow Sensor Not Learned' },
  { code: 'P0632', category: 'P', description: 'Odometer not Programmed' },
  { code: 'P0633', category: 'P', description: 'Immobilizer Key Not Learned' },
  { code: 'P0634', category: 'P', description: 'PCM/ECM/ECU Serial Number Mismatch' },
  { code: 'P0635', category: 'P', description: 'Power Steering Control Circuit' },
  { code: 'P0636', category: 'P', description: 'Power Steering Control Circuit Low' },
  { code: 'P0637', category: 'P', description: 'Power Steering Control Circuit High' },
  { code: 'P0638', category: 'P', description: 'Throttle Actuator Control Range/Performance Bank 1' },
  { code: 'P0639', category: 'P', description: 'Throttle Actuator Control Range/Performance Bank 2' },
  { code: 'P0640', category: 'P', description: 'Intake Air Heater Relay Control Circuit' },
  { code: 'P0641', category: 'P', description: 'Power Supply Relay Control Circuit' },
  { code: 'P0642', category: 'P', description: 'Power Supply Voltage Low' },
  { code: 'P0643', category: 'P', description: 'Power Supply Voltage High' },
  { code: 'P0644', category: 'P', description: 'Traction Control System Signal Fault' },
  { code: 'P0645', category: 'P', description: 'Air Conditioning Clutch Relay Control Circuit' },
  { code: 'P0646', category: 'P', description: 'Air Conditioning Clutch Relay Control Circuit Low' },
  { code: 'P0647', category: 'P', description: 'Air Conditioning Clutch Relay Control Circuit High' },
  { code: 'P0648', category: 'P', description: 'Immobilizer Lamp Control Circuit' },
  { code: 'P0649', category: 'P', description: 'Speed Control Lamp Control Circuit' },
  { code: 'P0650', category: 'P', description: 'Malfunction Indicator Lamp (MIL) Control Circuit' },
  { code: 'P0651', category: 'P', description: 'Power Steering Pressure Switch Relay Control Circuit' },
  { code: 'P0652', category: 'P', description: 'Sensor Reference Voltage B Circuit' },
  { code: 'P0653', category: 'P', description: 'Sensor Reference Voltage B Circuit Low' },
  { code: 'P0654', category: 'P', description: 'Engine RPM Output Circuit' },
  { code: 'P0655', category: 'P', description: 'Engine Power Output Relay Control Circuit' },
  { code: 'P0656', category: 'P', description: 'Fuel Level Output Circuit' },
  { code: 'P0657', category: 'P', description: 'Actuator Supply Voltage Circuit Open' },
  { code: 'P0658', category: 'P', description: 'Actuator Supply Voltage A Low' },
  { code: 'P0659', category: 'P', description: 'Actuator Supply Voltage A High' },
  { code: 'P0660', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit' },
  { code: 'P0661', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit Low' },
  { code: 'P0662', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit High' },
  { code: 'P0663', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit Bank 2' },
  { code: 'P0664', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit Bank 2 Low' },
  { code: 'P0665', category: 'P', description: 'Intake Manifold Tuning Valve Control Circuit Bank 2 High' },
  { code: 'P0666', category: 'P', description: 'PCM/ECM/ECU Backup Power Supply Low' },
  { code: 'P0667', category: 'P', description: 'PCM/ECM/ECU Backup Power Supply High' },
  { code: 'P0668', category: 'P', description: 'Hydraulic Pressure Low' },
  { code: 'P0669', category: 'P', description: 'Hydraulic Pressure High' },
  { code: 'P0670', category: 'P', description: 'Glow Plug Control Module Control Circuit' },
  { code: 'P0671', category: 'P', description: 'Glow Plug A Control Circuit' },
  { code: 'P0672', category: 'P', description: 'Glow Plug B Control Circuit' },
  { code: 'P0673', category: 'P', description: 'Glow Plug C Control Circuit' },
  { code: 'P0674', category: 'P', description: 'Glow Plug D Control Circuit' },
  { code: 'P0675', category: 'P', description: 'Glow Plug E Control Circuit' },
  { code: 'P0676', category: 'P', description: 'Glow Plug F Control Circuit' },
  { code: 'P0677', category: 'P', description: 'Glow Plug G Control Circuit' },
  { code: 'P0678', category: 'P', description: 'Glow Plug H Control Circuit' },
  { code: 'P0679', category: 'P', description: 'Glow Plug I Control Circuit' },
  { code: 'P0680', category: 'P', description: 'Glow Plug J Control Circuit' },
  { code: 'P0681', category: 'P', description: 'Glow Plug K Control Circuit' },
  { code: 'P0682', category: 'P', description: 'Glow Plug L Control Circuit' },
  { code: 'P0683', category: 'P', description: 'Glow Plug Control Module Control Circuit Low' },
  { code: 'P0684', category: 'P', description: 'Glow Plug Control Module Control Circuit High' },
  { code: 'P0685', category: 'P', description: 'Engine Control Power Relay Control Circuit' },
  { code: 'P0686', category: 'P', description: 'Engine Control Power Relay Control Circuit Low' },
  { code: 'P0687', category: 'P', description: 'Engine Control Power Relay Control Circuit High' },
  { code: 'P0688', category: 'P', description: 'Engine Control Power Relay Sense Circuit Low' },
  { code: 'P0689', category: 'P', description: 'Engine Control Power Relay Sense Circuit High' },
  { code: 'P0690', category: 'P', description: 'Engine Control Power Relay De-energized Too Early' },
  { code: 'P0691', category: 'P', description: 'Cooling Fan 1 Control Circuit Low' },
  { code: 'P0692', category: 'P', description: 'Cooling Fan 1 Control Circuit High' },
  { code: 'P0693', category: 'P', description: 'Cooling Fan 2 Control Circuit Low' },
  { code: 'P0694', category: 'P', description: 'Cooling Fan 2 Control Circuit High' },
  { code: 'P0695', category: 'P', description: 'Cooling Fan 3 Control Circuit Low' },
  { code: 'P0696', category: 'P', description: 'Cooling Fan 3 Control Circuit High' },
  { code: 'P0697', category: 'P', description: 'Sensor Reference Voltage C Circuit Low' },
  { code: 'P0698', category: 'P', description: 'Sensor Reference Voltage C Circuit High' },

  // ── P0700–P0799: Transmission ─────────────────────────────────────────
  { code: 'P0700', category: 'P', description: 'Transmission Control System Malfunction' },
  { code: 'P0701', category: 'P', description: 'Transmission Control System Range/Performance' },
  { code: 'P0702', category: 'P', description: 'Transmission Control System Electrical' },
  { code: 'P0703', category: 'P', description: 'Brake Switch B Circuit' },
  { code: 'P0704', category: 'P', description: 'Clutch Switch Input Circuit' },
  { code: 'P0705', category: 'P', description: 'Transmission Range Sensor A Circuit (PRNDL Input)' },
  { code: 'P0706', category: 'P', description: 'Transmission Range Sensor A Circuit Range/Performance' },
  { code: 'P0707', category: 'P', description: 'Transmission Range Sensor A Circuit Low' },
  { code: 'P0708', category: 'P', description: 'Transmission Range Sensor A Circuit High' },
  { code: 'P0709', category: 'P', description: 'Transmission Range Sensor A Circuit Intermittent' },
  { code: 'P0710', category: 'P', description: 'Transmission Fluid Temperature Sensor A Circuit' },
  { code: 'P0711', category: 'P', description: 'Transmission Fluid Temperature Sensor A Circuit Range/Performance' },
  { code: 'P0712', category: 'P', description: 'Transmission Fluid Temperature Sensor A Circuit Low' },
  { code: 'P0713', category: 'P', description: 'Transmission Fluid Temperature Sensor A Circuit High' },
  { code: 'P0714', category: 'P', description: 'Transmission Fluid Temperature Sensor A Circuit Intermittent' },
  { code: 'P0715', category: 'P', description: 'Input/Turbine Speed Sensor A Circuit' },
  { code: 'P0716', category: 'P', description: 'Input/Turbine Speed Sensor A Circuit Range/Performance' },
  { code: 'P0717', category: 'P', description: 'Input/Turbine Speed Sensor A Circuit No Signal' },
  { code: 'P0718', category: 'P', description: 'Input/Turbine Speed Sensor A Circuit Intermittent' },
  { code: 'P0719', category: 'P', description: 'Brake Switch B Circuit Low' },
  { code: 'P0720', category: 'P', description: 'Output Speed Sensor Circuit' },
  { code: 'P0721', category: 'P', description: 'Output Speed Sensor Circuit Range/Performance' },
  { code: 'P0722', category: 'P', description: 'Output Speed Sensor Circuit No Signal' },
  { code: 'P0723', category: 'P', description: 'Output Speed Sensor Circuit Intermittent' },
  { code: 'P0724', category: 'P', description: 'Brake Switch B Circuit High' },
  { code: 'P0725', category: 'P', description: 'Engine Speed Input Circuit' },
  { code: 'P0726', category: 'P', description: 'Engine Speed Input Circuit Range/Performance' },
  { code: 'P0727', category: 'P', description: 'Engine Speed Input Circuit No Signal' },
  { code: 'P0728', category: 'P', description: 'Engine Speed Input Circuit Intermittent' },
  { code: 'P0729', category: 'P', description: 'Gear Ratio Error' },
  { code: 'P0730', category: 'P', description: 'Automatic Transmission Range/Performance' },
  { code: 'P0731', category: 'P', description: 'Transmission Gear 1 Incorrect' },
  { code: 'P0732', category: 'P', description: 'Transmission Gear 2 Incorrect' },
  { code: 'P0733', category: 'P', description: 'Transmission Gear 3 Incorrect' },
  { code: 'P0734', category: 'P', description: 'Transmission Gear 4 Incorrect' },
  { code: 'P0735', category: 'P', description: 'Transmission Gear 5 Incorrect' },
  { code: 'P0736', category: 'P', description: 'Reverse Incorrect' },
  { code: 'P0737', category: 'P', description: 'Transmission Gear Neutral Incorrect' },
  { code: 'P0738', category: 'P', description: 'Engine Torque Signal Fault' },
  { code: 'P0739', category: 'P', description: 'Transmission Fluid Over Temperature' },
  { code: 'P0740', category: 'P', description: 'Transmission Fluid Temperature Switch Circuit' },
  { code: 'P0741', category: 'P', description: 'Transmission Fluid Circulation System Insufficient Flow' },
  { code: 'P0742', category: 'P', description: 'Transmission Fluid Temperature Switch Circuit High' },
  { code: 'P0743', category: 'P', description: 'Torque Converter Clutch Solenoid/Circuit' },
  { code: 'P0744', category: 'P', description: 'Torque Converter Clutch Solenoid/Circuit Intermittent' },
  { code: 'P0745', category: 'P', description: 'Pressure Control Solenoid A' },
  { code: 'P0746', category: 'P', description: 'Pressure Control Solenoid A Performance/Stuck Off' },
  { code: 'P0747', category: 'P', description: 'Pressure Control Solenoid A Stuck On' },
  { code: 'P0748', category: 'P', description: 'Pressure Control Solenoid A Electrical' },
  { code: 'P0749', category: 'P', description: 'Pressure Control Solenoid A Intermittent' },
  { code: 'P0750', category: 'P', description: 'Shift Solenoid A' },
  { code: 'P0751', category: 'P', description: 'Shift Solenoid A Performance/Stuck Off' },
  { code: 'P0752', category: 'P', description: 'Shift Solenoid A Stuck On' },
  { code: 'P0753', category: 'P', description: 'Shift Solenoid A Electrical' },
  { code: 'P0754', category: 'P', description: 'Shift Solenoid A Intermittent' },
  { code: 'P0755', category: 'P', description: 'Shift Solenoid B' },
  { code: 'P0756', category: 'P', description: 'Shift Solenoid B Performance/Stuck Off' },
  { code: 'P0757', category: 'P', description: 'Shift Solenoid B Stuck On' },
  { code: 'P0758', category: 'P', description: 'Shift Solenoid B Electrical' },
  { code: 'P0759', category: 'P', description: 'Shift Solenoid B Intermittent' },
  { code: 'P0760', category: 'P', description: 'Shift Solenoid C' },
  { code: 'P0761', category: 'P', description: 'Shift Solenoid C Performance/Stuck Off' },
  { code: 'P0762', category: 'P', description: 'Shift Solenoid C Stuck On' },
  { code: 'P0763', category: 'P', description: 'Shift Solenoid C Electrical' },
  { code: 'P0764', category: 'P', description: 'Shift Solenoid C Intermittent' },
  { code: 'P0765', category: 'P', description: 'Shift Solenoid D' },
  { code: 'P0766', category: 'P', description: 'Shift Solenoid D Performance/Stuck Off' },
  { code: 'P0767', category: 'P', description: 'Shift Solenoid D Stuck On' },
  { code: 'P0768', category: 'P', description: 'Shift Solenoid D Electrical' },
  { code: 'P0769', category: 'P', description: 'Shift Solenoid D Intermittent' },
  { code: 'P0770', category: 'P', description: 'Shift Solenoid E' },
  { code: 'P0771', category: 'P', description: 'Shift Solenoid E Performance/Stuck Off' },
  { code: 'P0772', category: 'P', description: 'Shift Solenoid E Stuck On' },
  { code: 'P0773', category: 'P', description: 'Shift Solenoid E Electrical' },
  { code: 'P0774', category: 'P', description: 'Shift Solenoid E Intermittent' },
  { code: 'P0775', category: 'P', description: 'Pressure Control Solenoid B' },
  { code: 'P0776', category: 'P', description: 'Pressure Control Solenoid B Performance/Stuck Off' },
  { code: 'P0777', category: 'P', description: 'Pressure Control Solenoid B Stuck On' },
  { code: 'P0778', category: 'P', description: 'Pressure Control Solenoid B Electrical' },
  { code: 'P0779', category: 'P', description: 'Pressure Control Solenoid B Intermittent' },
  { code: 'P0780', category: 'P', description: 'Shift/Timing Solenoid Malfunction' },
  { code: 'P0781', category: 'P', description: 'Shift Solenoid F Performance/Stuck Off' },
  { code: 'P0782', category: 'P', description: 'Shift Solenoid F Stuck On' },
  { code: 'P0783', category: 'P', description: 'Shift Solenoid F Electrical' },
  { code: 'P0784', category: 'P', description: 'Shift Solenoid F Intermittent' },
  { code: 'P0785', category: 'P', description: 'Shift/Timing Solenoid Control Circuit' },
  { code: 'P0786', category: 'P', description: 'Shift/Timing Solenoid Control Circuit Range/Performance' },
  { code: 'P0787', category: 'P', description: 'Shift/Timing Solenoid Control Circuit Low' },
  { code: 'P0788', category: 'P', description: 'Shift/Timing Solenoid Control Circuit High' },
  { code: 'P0789', category: 'P', description: 'Shift/Timing Solenoid Control Circuit Intermittent' },
  { code: 'P0790', category: 'P', description: 'Normal/Power Selectable Shift Logic Circuit' },
  { code: 'P0791', category: 'P', description: 'Intermediate Shaft Speed Sensor Circuit' },
  { code: 'P0792', category: 'P', description: 'Intermediate Shaft Speed Sensor Circuit Range/Performance' },
  { code: 'P0793', category: 'P', description: 'Intermediate Shaft Speed Sensor Circuit No Signal' },
  { code: 'P0794', category: 'P', description: 'Intermediate Shaft Speed Sensor Circuit Intermittent' },
  { code: 'P0795', category: 'P', description: 'Pressure Control Solenoid C' },
  { code: 'P0796', category: 'P', description: 'Pressure Control Solenoid C Performance/Stuck Off' },
  { code: 'P0797', category: 'P', description: 'Pressure Control Solenoid C Stuck On' },
  { code: 'P0798', category: 'P', description: 'Pressure Control Solenoid C Electrical' },
  { code: 'P0799', category: 'P', description: 'Pressure Control Solenoid C Intermittent' },

  // ── Common Manufacturer / Network P1xxx examples ──────────────────────
  { code: 'P1000', category: 'P', description: 'OBD-II Monitor Testing Not Complete (Manufacturer Specific)' },
  { code: 'P1101', category: 'P', description: 'Mass Air Flow Sensor Out of Self-Test Range (Ford)' },
  { code: 'P1300', category: 'P', description: 'Ignition Coil Primary Circuit Malfunction (Manufacturer Specific)' },
  { code: 'P1450', category: 'P', description: 'Unable to Bleed Up Fuel Tank Vacuum (Manufacturer Specific)' },

  // ── B0xxx: Body ─────────────────────────────────────────────────────
  { code: 'B0001', category: 'B', description: 'Driver Frontal Stage 1 Deployment Control' },
  { code: 'B0010', category: 'B', description: 'Passenger Frontal Stage 1 Deployment Control' },
  { code: 'B0020', category: 'B', description: 'Driver Side Deployment Control' },
  { code: 'B0030', category: 'B', description: 'Passenger Side Deployment Control' },
  { code: 'B0051', category: 'B', description: 'Driver Seat Belt Switch Circuit' },
  { code: 'B0052', category: 'B', description: 'Passenger Seat Belt Switch Circuit' },
  { code: 'B0080', category: 'B', description: 'Left Side Curtain Deployment Control' },
  { code: 'B0081', category: 'B', description: 'Right Side Curtain Deployment Control' },
  { code: 'B0092', category: 'B', description: 'Frontal Crash Sensor Circuit' },
  { code: 'B0100', category: 'B', description: 'Occupant Classification System Circuit' },
  { code: 'B0111', category: 'B', description: 'Front Sensor Internal Fault' },
  { code: 'B1000', category: 'B', description: 'ECU Malfunction (Body Control Module)' },
  { code: 'B1318', category: 'B', description: 'Battery Voltage Low' },
  { code: 'B1342', category: 'B', description: 'ECU / Module Is Defective' },
  { code: 'B1519', category: 'B', description: 'Battery/Power Feed to Sensing/Diagnostic Module Circuit' },
  { code: 'B2477', category: 'B', description: 'Door Ajar Switch Circuit' },
  { code: 'B2800', category: 'B', description: 'Anti-Theft System Fault' },
  { code: 'B1650', category: 'B', description: 'Climate Control Blower Motor Circuit Malfunction' },
  { code: 'B1651', category: 'B', description: 'HVAC Blend Door Actuator Circuit Malfunction' },
  { code: 'B1004', category: 'B', description: 'Power Window Switch Circuit Malfunction' },

  // ── C0xxx: Chassis ──────────────────────────────────────────────────
  { code: 'C0035', category: 'C', description: 'Left Front Wheel Speed Sensor Circuit' },
  { code: 'C0040', category: 'C', description: 'Right Front Wheel Speed Sensor Circuit' },
  { code: 'C0045', category: 'C', description: 'Left Rear Wheel Speed Sensor Circuit' },
  { code: 'C0050', category: 'C', description: 'Right Rear Wheel Speed Sensor Circuit' },
  { code: 'C0055', category: 'C', description: 'Yaw Rate Sensor Circuit Malfunction' },
  { code: 'C0060', category: 'C', description: 'Left Front ABS Solenoid #1 Circuit' },
  { code: 'C0065', category: 'C', description: 'Right Front ABS Solenoid #1 Circuit' },
  { code: 'C0110', category: 'C', description: 'Pump Motor Circuit Malfunction (ABS)' },
  { code: 'C0121', category: 'C', description: 'Valve Relay Circuit Malfunction (ABS)' },
  { code: 'C0161', category: 'C', description: 'Traction Control System Disabled Switch Circuit' },
  { code: 'C0200', category: 'C', description: 'Steering Angle Sensor Circuit Malfunction' },
  { code: 'C0221', category: 'C', description: 'Left Front Wheel Speed Out of Range' },
  { code: 'C0245', category: 'C', description: 'Right Rear Wheel Speed Out of Range' },
  { code: 'C0300', category: 'C', description: 'Traction Control System Malfunction' },
  { code: 'C0450', category: 'C', description: 'Brake Pedal Travel Sensor Circuit Malfunction' },
  { code: 'C0561', category: 'C', description: 'Calibration/Configuration Data Incompatible (Chassis Module)' },
  { code: 'C0710', category: 'C', description: 'Low Tire Pressure — Left Front' },
  { code: 'C0715', category: 'C', description: 'Low Tire Pressure — Right Front' },
  { code: 'C0720', category: 'C', description: 'Low Tire Pressure — Left Rear' },
  { code: 'C0725', category: 'C', description: 'Low Tire Pressure — Right Rear' },
  { code: 'C0800', category: 'C', description: 'TPMS Sensor Battery Low' },

  // ── U0xxx: Network / Communication ─────────────────────────────────
  { code: 'U0001', category: 'U', description: 'High Speed CAN Communication Bus' },
  { code: 'U0100', category: 'U', description: 'Lost Communication with ECM/PCM' },
  { code: 'U0101', category: 'U', description: 'Lost Communication with TCM' },
  { code: 'U0121', category: 'U', description: 'Lost Communication with ABS Control Module' },
  { code: 'U0140', category: 'U', description: 'Lost Communication with Body Control Module' },
  { code: 'U0155', category: 'U', description: 'Lost Communication with Instrument Panel Cluster' },
  { code: 'U0164', category: 'U', description: 'Lost Communication with HVAC Control Module' },
  { code: 'U0184', category: 'U', description: 'Lost Communication with Radio' },
  { code: 'U0195', category: 'U', description: 'Lost Communication with Battery Energy Control Module' },
  { code: 'U0300', category: 'U', description: 'Internal Control Module Software Incompatibility' },
  { code: 'U0401', category: 'U', description: 'Invalid Data Received From ECM/PCM' },
  { code: 'U0402', category: 'U', description: 'Invalid Data Received From TCM' },
  { code: 'U0415', category: 'U', description: 'Invalid Data Received From ABS Control Module' },
  { code: 'U0422', category: 'U', description: 'Invalid Data Received From Body Control Module' },
  { code: 'U1000', category: 'U', description: 'Class 2 Communication Malfunction (Manufacturer Specific)' },
];

export function searchObdCodes(query: string, limit = 8): ObdCode[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  const results = OBD_CODES.filter(
    (c) => c.code.startsWith(q) || c.description.toUpperCase().includes(q)
  );
  return results.slice(0, limit);
}
